Cargo.toml, src/cursor.rs, src/lib.rs, src/types/mod.rs
* Adds a `Cursor` trait that captures the format-agnostic, system-level parser functionality needed to navigate within an Ion stream and read the values encountered into native Rust data types.
* All `read_{data_type}` functions are named after the Rust data type they produce rather than the Ion data type they represent. This accommodates adding other representations in the future. I intend to add other flavors (e.g. `read_i32`, `read_u32`, `read_u64`, etc) soon.
* Adds a dependency on the `chrono` and `bigdecimal` crates to represent `timestamp` and `decimal` respectively.
* Adds a `SymbolId` type. It's currently a type alias for `usize`, allowing it to be used as an index into various containers.
By submitting this pull request, I confirm that my contribution …
=> Added Cursor trait.

.github/workflows/rust.yml, .gitmodules, Cargo.toml, tests/good.rs
*Issue #, if available:* Related to #18.
* Adds `ion-tests` as a git submodule.
* Stubs out reading the `good` Ion files from `ion-tests`. Once #22 is merged we can implement this fully for good `.10n` files.
=> Add ion-tests submodule

Cargo.toml, examples/read_all_values.rs, src/binary/cursor.rs, src/binary/mod.rs, src/binary/var_uint.rs, src/data_source.rs, src/lib.rs
* Adds an example, `read_all_values`, that recursively visits all values in the provided binary Ion file and reads each scalar into a native Rust type.
* Makes a few data types public.
* Configures the `release` build target to perform extra optimizations.
* Sets `#[inline(always)]` on some functions that were hotspots in profiled runs of `read_all_values`.
=> Bin cursor inlining

Cargo.toml, src/binary/cursor.rs, src/binary/mod.rs, src/constants.rs, src/cursor.rs, src/lib.rs, src/reader.rs, src/symbol_table.rs
Added:
* SymbolTable
* Format-agnostic impl of Reader
* SymbolTableEventHandler trait
* New cursor function `raw_value_bytes()`, which allows safe access to a value's unparsed bytes without advancing the cursor. This is helpful for performance-sensitive searching/filtering and is only available for cursors over in-memory data sources like byte arrays.
Moved some functions from `BinaryIonCursor` into the `Cursor` trait itself:
* `depth()`
* `string_ref_map()`
=> Added SymbolTable and Reader

src/binary/cursor.rs, src/binary/mod.rs
Adds logic to track the byte offsets for a value's field ID and annotations (if present), header, and
encoded value.
Also adds functions to get byte slices for each subfield's representation to the in-memory Reader
implementation.
=> Tracking subfield offsets

.github/workflows/rust.yml
Also Updates `actions/checkout@v2` to use recursive submodule checkout.
=> Adds Github Action configurations for macOS and Windows.

ion-c-sys/src/lib.rs
This code I believe was not operating correctly and potentially
accessing memory in an illegal way. Specifically, it allocated
a zero byte struct and returned a pointer to said struct.
These zero byte structs were forward declarations, so the correct
way to use them are as direct pointers that get "filled" in by
IonC.
I updated the tests to just initialize them as null pointers.
Note that this is a PR against my feature branch `ion-c` not `master`.
=> Removes make_* from test code.

ion-c-sys/build.rs, ion-c-sys/src/lib.rs
Adds some full cookbook style API documentation for direct Ion C API interaction.
* Adds `Default` derivation for `bindgen` APIs.
* Implements examples directly against the low-level API.
=> Adds ion-c-sys crate example doc tests.

ion-c-sys/src/lib.rs, ion-c-sys/src/result.rs
* Adds `IonCError` to model `iERR` in a more idiomatic way.
* Adds type alias for `IonCResult`.
* Adds `ionc!` macro that wraps Ion C API calls with `unsafe` and
conversion to `IonCResult`.
* Adds `as_str()` for `ION_STRING` to get a `str` slice in a convenient
way.
* Retrofits unit tests and doc tests to use the new APIs.
First step towards #37.
=> Adds call wrapper, Result/Error integration.

ion-c-sys/Cargo.toml, ion-c-sys/src/lib.rs
* Adds `ion_type!` macro to generate the various `ION_TYPE_*` constants.
These are not generated by bindgen.  This uses the `paste` proc macro
crate to generate identifiers.
* Adds `ION_STRING::from` for the common case against a `&mut str`.
If there is a use case, we could consider adding unsafe versions
against `&str` because *most* cases are not actually mutating the
underlying `*u8`.
* Updates unit/doc tests to use these APIs.
More progress towards #37.
=> Adds ION_TYPE constants and ION_STRING::from.

tests/good.rs
This has been annoying me for a while due to compiler warnings--I was going to make it `#[allow(dead_code)]`, but I don't even think this constant belongs in this file.
=> Removes unused constant from 'good' tests.

ion-c-sys/src/lib.rs, ion-c-sys/src/reader.rs, ion-c-sys/src/result.rs, ion-c-sys/src/writer.rs
* Adds `IonCReaderHandle` and `IonCWriterHandle` which are smart pointer
types over `hREADER` and `hWRITER` respectively that ensure that the
Ion C close methods get invoked in RAII style code.
* Adds TryFromIntError to make doing safe coercions from things like
`usize` to `i32` easier within the context of `IonCError`.
More progress on #37.
=> Adds reader/writer modules.

ion-c-sys/src/lib.rs, ion-c-sys/src/reader.rs, ion-c-sys/src/result.rs, ion-c-sys/src/string.rs, ion-c-sys/src/writer.rs
Pushes the most commonly used Ion C reader APIs as safer, easier to use
APIs in `IonCReaderHandle`.
Also:
* Changes `IonCResult` from `()` value to  `IonCResult<T>` to be more
useful for these new APIs.
* Adds `From` trait support for `Utf8Error` to `IonCError`.
* Adds `IonCStringRef` to provide lifetime safe borrows to `ION_STRING`.
* Makes `IonCError` fields public.
* Adds from_bytes`/`try_as_bytes` to `ION_STRING` and adds
doc tests.
- Renames `from` to `from_str` and `as_str` to `try_as_str`.
* Makes various small functions inline.
* Updates top-level doc test reader example to use new APIs.
More progress on #37.
**Note**: I did not port the unit tests to the new APIs because I am still refactoring those to be parameterized in another branch.
By submitting this pull request, I confirm …
=> Adds a high-level facade on IonCReaderHandle.

ion-c-sys/src/lib.rs, ion-c-sys/src/reader.rs, ion-c-sys/src/writer.rs
This makes using common Ion C APIs much easier and more idiomatic
to Rust.
* Adds `new_buf_mode` to be an easier entry point to enable binary/text
modes.
* Adds writer APIs over `ionc!` calls with doc examples.
* Adds support for immutable slices for IonCReaderHandle.
* Removes mutability requirement for input buffer as Ion C does not
mutate read buffers (modulo bugs).
* Updates main doc example tests to use new APIs.
* Changes `ION_STRING::from_str` to `from_mut_str`
* Changes `ION_STRING::from_bytes` to `from_mut_bytes`
* Adds internal `ION_STRING::from_str` for immutable cases.
Implements #47.
=> Adds Facade API on IonCWriterHandle.

ion-c-sys/src/writer.rs
* Adds `IonCFieldWriterContext` which is a partial bind through references of the
field name and writer handle.
* Changes `set_field_name` to `start_field_name`.
* Adds `IonCValueWriter` trait to capture the value writing API surface.
* Updates doc test with this API.
Resolves #51.
=> Adds Lifetime Safe Field Writing.

ion-c-sys/src/lib.rs, ion-c-sys/src/reader.rs, ion-c-sys/src/result.rs, ion-c-sys/src/writer.rs
Did a cleanup run of `cargo fmt` just to make the code follow idiomatic code conventions.
=> Cleans up the code with cargo fmt.

ion-c-sys/src/lib.rs, ion-c-sys/src/reader.rs, ion-c-sys/src/result.rs, ion-c-sys/src/string.rs, ion-c-sys/src/writer.rs
Also:
* Adds `Derive(PartialEq)` to `IonCError`.
* Removes duplication comment around `IonCReaderHandle` and `IonCWriterHandle`.
At this point they are both so different that it doesn't matter.
* Refactors `IonCStringRef` to `StrSliceRef` and makes it just over a `&str`
versus `ION_STRING`. The use casees in the library are all UTF-8 results
from the reader. This tightens up the implementation and makes it
marginally easier to use.
- Removes `DerefMut` implementation.
* Adds `StrSlicesRef` for APIs that return multiple `&str` (e.g. annotations).
* Adds low-level APIs to `ION_STRING` to manage lifetimes of references generated.
* Various cleanup of the `ION_STRING` APIs to make them safer.
* Changes `get_field_name` and `read_string` to use `StrRef`.
* Changes `get_annotations` to return …
=> Implementation of IonCReaderHandle get_annotations.

.github/workflows/rust.yml, README.md, ion-c-sys/README.md
* Adds a README.md for `ion-c-sys` crate.
* Changes the Github Action CI workflow name to `Build`
to make a prettier badge.
* Adds badge URL to our master CI build workflow in READMEs.
=> Minor cleanup to README.md

ion-c-sys/src/writer.rs
Changes `IonCFieldWriterContext` to a unified `IonCAnnotationsFieldWriterContext`.
This enables the partial application function of building up annotations/field name
to be done completely with references and writing either or both for a particular
value.
Resolves #56.
=> [ion-c-sys] Implements Annotation Writing.

ion-c-sys/tests/value.rs
* Adds `bin` field for test cases.
* Adds Ion binary equivalent `u8` array constants for each test.
* Adds a `TestMode` to create a binary/text testing matrix.
* Removes `reader.get_type()` before `next()` assertion because of
an Ion C bug (amzn/ion-c#186).
Resolves #63. 
=> [ion-c-sys] Ion binary reader API tests.

ion-c-sys/Cargo.toml, ion-c-sys/src/int.rs, ion-c-sys/src/lib.rs, ion-c-sys/src/reader.rs, ion-c-sys/src/result.rs, ion-c-sys/src/string.rs, ion-c-sys/src/writer.rs
Adds support for converting to/from `num_bigint::BigInt`
and `ION_INT` and reader/writer support.
* Adds `IonIntPtr` as safe pointer to `ION_INT`.
* Adds some module documentation.
* Updates Cargo.toml to have more explicit version
requirements.
* Adds `rstest_reuse` crate for reusing test tables.
Resolves #50.
=> [ion-c-sys] Adds Big Integer Support.

Cargo.toml, examples/read_all_values.rs, ion-c-sys/Cargo.toml, tests/good.rs
The original name is taken on crates.io.
* Updates `ion-c-sys` to 0.2.0 (adds big integer support).
* Adds version dependency on `ion-c-sys` from `ion-rs`.
* Updates examples/integration tests to use `ion_rs`.
=> Renames ion-rust to ion-rs

ion-c-sys/Cargo.toml, ion-c-sys/bindings.h, ion-c-sys/build.rs, ion-c-sys/src/decimal.rs, ion-c-sys/src/int.rs, ion-c-sys/src/lib.rs, ion-c-sys/src/reader.rs, ion-c-sys/src/writer.rs
Implements `bigdecimal::BigDecimal` conversions to/from
`ION_DECIMAL`.
* Adds `IonDecimalPtr` smart pointer to manage `ION_DECIMAL` instances.
* Adds `ION_DECIMAL` methods:
- `try_assign_bigdecimal` to convert from `BigDecimal`.
- `try_to_bigdecimal` to convert to `BigDecimal`.
* Adds `IonCReaderHandle.read_bigdecimal`.
* Adds `IonCWriterHandle.write_bigdecimal`.
* Renames `ION_INT` conversion methods to be consistent.
* Works around construction of `ION_DECIMAL` from `ION_INT` (#80).
- Adds `bindings.h` header and updates `build.rs` to expose internal
Ion decimal APIs.
* Adds error cases and test skips for:
- `ION_INT` to `decNumber` conversion problems (#79).
There is no limit on *reading*, however default options are still 37
digits in Ion C.  Currently, *writing* decimals with over 34 …
=> [ion-c-sys] Adds support for BigDecimal.

ion-c-sys/Cargo.toml, ion-c-sys/src/decimal.rs, ion-c-sys/src/lib.rs, ion-c-sys/src/reader.rs, ion-c-sys/src/result.rs, ion-c-sys/src/timestamp.rs, ion-c-sys/src/writer.rs
Adds `IonDateTime` which wraps `chrono::DateTime` with the concept of
*precision* and *offset kind* to completely support the timestamp data
model.
* Adds conversion methods in `ION_TIMESTAMP`:
- `try_to_iondt()` to convert to `IonDateTime`
- `try_assign_from_iondt()` to convert from `IonDateTime`.
* Adds `IonCReaderHandle.read_datetime()`.
* Adds `IonCWriterHandle.write_datetime()`.
* Adds `timestamp` module:
- Adds `TSOffsetKind` to cover the concept of *unknown offset*
(i.e. `-00:00`).
- Adds `TSPrecision` to cover Ion timestamp precision, including
fractional precision via `Mantissa` which models digits or
higher-precision fraction.
* Adds `additional` message field on `IonCError` to be more descriptive.
* Adds `IonDecimalPtr.try_from_decquad()`.
Resolves #43.
By submitting this pull …
=> [ion-c-sys] Adds Timestamp Support.

ion-c-sys/src/lib.rs, ion-c-sys/tests/value.rs
* Minor cleanup on BigDecimal conversion error message.
* Makes the dereference for the `ION_DECIMAL` explicit to get at fraction
because it makes CLion confused (and is technically clearer as to what is going on).
Related to #42 and #43.
=> Adds value read tests for decimal/timestamp.

Cargo.toml, ion-c-sys/Cargo.toml
Release candidate for crates.io with Timestamp support.
=> [ion-c-sys] Bumps version to 0.4.0

Cargo.toml, ion-c-sys/Cargo.toml
* `bindgen` 0.54.1 was yanked on crates.io.
* Bumps `ion-c-sys` version.
=> Fixes bindgen dependency.

Cargo.toml
*Issue #, if available:* Fixes #93.
Dependencies declared in `Cargo.toml` now use `^` syntax rather than `~`.
=> Dependencies use ^ instead of ~

ion-c-sys/src/string.rs
Small ergonomic improvements.
* Implements `AsRef<str>` for `StrSliceRef`.
* Implements `AsRef<[&'a str]>` for `StrSlicesRef`.
=> [ion-c-sys] Adds `AsRef` for the ION_STRING reference wrappers.

ion-c-sys/src/lib.rs, ion-c-sys/src/reader.rs, ion-c-sys/src/writer.rs
* Adds `IonCAnnotationsFieldWriter` which is a functional way to capture
the application of annotations and field name.
* Makes `IonCAnnotationsFieldWriterContext` generic and implemented in
terms of the above.
* Changes `from_buf` to `try_from_buf` to be more consistent in `IonCReaderHandle`.
Resolves #85.
=> [ion-c-sys] Refactors the traits for `IonCReader` and `IonCWriter`.

Cargo.toml, ion-c-sys/Cargo.toml, src/binary/cursor.rs
Note that due to commit [30b79b7][1] in akubera/bigdecimal-rs, `f64` conversion must use `TryFrom` and not `From`, so minor fix to the unit tests are included.
[1]: https://github.com/akubera/bigdecimal-rs/commit/30b79b7601095e348eed845b116352f3feeb5fd0
=> Bumps `bigdecimal` and `num-bigint` dependencies.

ion-c-sys/src/lib.rs
Fixes #102
Type `c_char` is sometimes signed or unsigned depending on platform,
we had code doing explicit casts to the underlying `i8` on GCC/Clang x86-64,
but other platforms are known to be `u8` which causes build failures
(e.g. AArch64).
=> [ion-c-sys] Fixes some `c_char` pointer casts to make them portable.

Cargo.toml, ion-c-sys/Cargo.toml
Makes it easier to build with packages that depend on bindgen 0.54.
=> [ion-c-sys] Changes bindgen dependency and bumps version

ion-c-sys/build.rs
RHEL/CentOS/AL2 generates an output directory of `lib64` versus
`lib` on the other platform, this supports either modality.
Fixes #106.
=> [ion-c-sys] Adds library path to lib/lib64 for Ion C.

Cargo.toml
This is less strict than what we have currently, which is patch version.
=> Makes ion-rs depend on ion-c-sys minor version.

src/binary/cursor.rs
The `EncodedLevel` struct is just large enough that variations of it (like `Option<EncodedLevel>` and `Result<EncodedLevel, _>`) can cross [LLVM's threshold for using `memcpy` to move values around](https://github.com/rust-lang/rust/pull/64302#issuecomment-529840404). This shows up in profiling as substantial overhead in the `step_in` and `step_out` functions, which move instances of `EncodedLevel` to and from a `Vec` of container levels.
In a particularly deeply nested test file (a single struct with ~800 levels of nested child structs), this caused the reader to be painfully slow. A 15MB file took ~230ms to read through with `next()`/`step_in()`/`step_out()`, loading each scalar value encountered.
This PR shrinks the `EncodedLevel` struct by:
* Replacing a …
=> Shrank EncodedLevel to speed up step_in/step_out.

src/binary/cursor.rs, src/binary/int.rs, src/binary/mod.rs, src/binary/uint.rs, src/binary/var_int.rs, src/binary/var_uint.rs, src/binary/writer.rs, src/cursor.rs, src/reader.rs
This PR adds a system-level binary writer to the crate.
Notes:
* Rather than not supporting `timestamp` fractional seconds at all, the reader and writer now support nanosecond precision (and *only* nanosecond precision). This is a stepping stone to full support for timestamps.
*Out of scope for this PR:*
* A user-level binary writer, with symbol table management and LST appends.
* A proper `SymbolToken`-centric API.
* A way to specify precision when writing a given `DateTime` as a timestamp. (#17 will be updated to indicate that the reader and writer now support nanoseconds precision and nothing else.)
=> Added system-level binary writer.

Cargo.toml, src/lib.rs, src/result.rs
Fixes #110.
* Switched from `failure` to the more  modern `thiserror` crate for generating  boilerplate trait implementations.
* IonError now implements the trait `std::error::Error`, a prerequisite for using it with the `anyhow` crate.
* An IonError can now retain the original `io::Error` or `fmt::Error` that caused it.
=> Updates to the IonError type.

ion-c-sys/src/timestamp.rs, src/binary/cursor.rs, src/binary/int.rs, src/binary/var_int.rs, src/binary/var_uint.rs, src/binary/writer.rs, src/cursor.rs, src/reader.rs, src/result.rs, src/system_event_handler.rs, src/types/type.rs
Runs `rustfmt` on the entire codebase for consistency. This PR contains no logic changes, just reformatting. A few functions have been flagged with the `#[rustfmt::skip]` annotation because they have comments that are carefully spaced.
After this is merged, I'll add `rustfmt --check` to the CI build.
=> Ran rustfmt

src/text/parsers/clob.rs, src/text/parsers/mod.rs, src/text/reader.rs
*Issue #125*
This PR works on creating text `clob` parser. 
*Changes:*
- Created `parse_clob` similar to `string` parser with an extra parsing step to verify `{{}}` for `clob` value.
- Instead of returning `string` in the helper parsing methods, changed to use `Vec<u8>` for correctly parsing extended ASCII values. 
- Changed the order of arguments for `assert_eq!` to be same as `parse_equals` method for consistency.
```
assert_eq!(actual, expected)
actual -> value parsed with ion-rust text parsers 
expected -> expected value to be used for equivalence
```
*Test:*
Added unit tests for `clob` type check and parsing tests.
=> added changes for text clob parsing

src/lib.rs, src/value/borrowed.rs, src/value/mod.rs, src/value/owned.rs
Provides an _borrowed_/_owned_ implementations of the traits in the `value` module.  The borrowed implementation is tied to a lifetime for string/binary data (but potentially more in the future).  The owned implementation is completely self contained.
* Defines `SymbolToken` and `ImportSource` traits that is the basis for full symbol/field name/annotation support in `ion-rs`, but also is required for the `Element` trait.
* APIs that return `Iterator` types currently use a `Box` to avoid the need for generic associated types (GAT).
* Captures the variance of integers in Ion with the `IntAccess` trait and the `AnyInt` enum.
* Currently implements the `Struct` trait via `Vec` of tuples, which will have to be refactored for O(N) access but is suitable for the iterator APIS.
Starts to address …
=> Adds a preliminary `Element` DOM-like API.

src/value/borrowed.rs, src/value/mod.rs, src/value/owned.rs
This PR works on creating methods for `Sequence` and `Struct` in Value API.
*Completed Tasks:*
- Added `Eq`, `PartialEq` and `Hash` implementations for` Borrowed/OwnedSymbolTokens`.
- Added Sequence methods: `get`, `len`, `is_empty`, `pop`, `push`
- Added Struct methods: `get`, `get_all`
- Struct uses a `HashMap` with `(key, values) -> (SymbolToken, Vec<Element>)`
*TODO:*
- Remove usage of `unwrap()` as it will panic on `None`.
- Add tests for this implementation
*Base PR:* https://github.com/amzn/ion-rust/pull/131
=> Added methods for Sequence and Struct

src/value/borrowed.rs, src/value/mod.rs, src/value/owned.rs
*Issue #114 *
This issues fills in the API methods for `Sequence` and `Struct` on the Value API.
*Changes:*
- Added `Sequence` methods: `get`, `len`, `is_empty`
- Added `Struct` methods: `get`, `get_all`
- `Struct` uses a `HashMap` with `(key, values) -> (String, Vec<(SymbolToken, Element)>)` as well as  a `Vec<(Symboltoken, Element)>` to store fields with no text `SymbolToken`
=> Added methods for Sequence and Struct (#132)

src/value/borrowed.rs, src/value/mod.rs, src/value/owned.rs
*Issue #134*
This PR works on using `Rc<String>` instead of `String` for `OwnedSymbolToken`, `OwnedImportSource`, `OwnedStruct`.
=> Changed OwnedSymbolToken, OwnedImportSource, OwnedStruct from using String to Rc<String>

.github/workflows/rust.yml, src/value/borrowed.rs, src/value/mod.rs, src/value/owned.rs
* Ergonomic improvement of constructing a borrowed/owned `Struct` easier from an interator.
(see #136).
* Adds a doc test that demonstrates the above constructor and the generic API in use.
* Also did some minor clean-up around some of the `get`/`get_all` implementation to
be a little less verbose.
Resolves #142.
=> Adds generic `get`/`get_all` for `Struct` in terms of `AsRef<str>`.

src/value/borrowed.rs, src/value/mod.rs, src/value/owned.rs
*Issue #139*
This PR works on filling in rest of the scalar value types for Element API.
*Changes:*
Added following scalar types with this PR:
- Float
- Decimal
- Timestamp
- Boolean
- Blob
- Clob
=> added remaining scalar value types for Element API

src/value/borrowed.rs, src/value/mod.rs, src/value/owned.rs
Increases coverage for that module from 54% to 72% as measured with grcov.
Creates a dispatch table style approach where all the `asXXX` methods
are negatively asserted and each test case "overrides" the negative
assertion cases with its own.
Also did some API cleanup to make things more consistent and easier to test:
* Renames `as_float` to `as_f64`.
* Consolidates `as_blob` and `as_clob` to `as_bytes`.
* `PartialEq`/`Eq` for `AnyInt` to facilitate testing.
Addresses some of #146 and is based on work that @desaikd started with #147.
=> Refactors `value::owned` unit tests to be more parameterized.

Cargo.toml, src/value/borrowed.rs, src/value/mod.rs, src/value/owned.rs
*Issue #146*
This PR works on using fixtures for `Element` API unit tests.
*Changes:*
- created a fixture for creating `owned_element` to be used for unit tests.
- added `rstest` to `Cargo.toml`
=> Added unit tests with fixture for `Element` API

src/value/borrowed.rs, src/value/owned.rs
Makes `Sequence::get` implementations to avoid extra wrapping
by using `get` instead of the indexing operator.  Also renames a test
method `mk_ts` to `make_timestamp` to be less obtuse.
=> Cleanup as per post-merge feedback from @zslayton on #132 and #148.

src/value/mod.rs, src/value/owned.rs
Adds new top-level constructor functions for `OwnedSymbolToken` that
makes it more ergonomic.  Makes the low-level `OwnedSymbolToken::new`
private in preference of the new functions.
Adds annotation tests on the elements in various equivalences.
TODO refactor this to `borrowed`, add non-equivalence, and refactor
to smaller units.
This is based on #152.
=> Refactors `OwnedElement` tests to do some equivalence testing.

src/value/mod.rs, src/value/owned.rs
*Issue #149 , #147*
This PR works on creating `PartialEq` and `Eq` for `value::Owned` types and adds unit tests for container types.
*Changes:*
- Added `PartialEq` and `Eq` for `OwnedSymbolToken`, `OwnedImportSource`, `OwnedStruct`, `OwnedSequence`, `OwnedElement`. 
- Added unit tests for container types.
=> added PartialEq/ Eq for value::owned and added  unit tests for container types

.github/workflows/coverage.yml, README.md
* Adds codecov.io integration in Workflow.
* Adds coverage badge.
TODO full app integration with codecov.io like we have in other repos.
Resolves #150.
=> Adds `grcov` GH Action Workflow.

src/value/mod.rs, src/value/owned.rs
*Issue #161*
This PR works on adding check for `no_text_fields` in `OwnedStruct` `PartialEq`.
*Changes:*
- added `no_text_fields` check inside `PartialEq` for `OwnedStruct` .
*Tests:*
Added unit tests for `no_text_fields`.
=>  Changed `OwnedStruct``PartialEq` to use `no_text_fields` for equivalence

src/value/mod.rs
Our symbol table explainer code block was annotated as `ignore` this is
not quite right as it is not even Rust code so annotating it with
`plain` is more appropriate.
=> Fixes doc test to plain text.

.github/workflows/coverage.yml
Coverage relies on `nightly`, and the `default` profile seems to be a bit more stable.
I noticed that 2021-04-11 nightly started breaking for `clang_sys`.  It seems that the version one installs by default for nightly was a few weeks behind.  I am trying setting this profile in the hopes that we get a more "stable" nightly for our coverage CI.  If we run into more problems, we might have to start pinning the nightly version to keep things more reliable.
Hopefully someday soon we won't have to rely on unstable `-Zprofile` for code coverage.
=> Changes rustup profile to `default` for `nightly`.

.github/workflows/coverage.yml
Nightly builds can be really unstable--and has shown to break our
pipeline.  This pins the version to make it explicit to which
version of the compiler we use to generate code coverage.
=> Pins Code Coverage to `nightly-2021-03-23`.

src/value/borrowed.rs, src/value/mod.rs
*Issue #157*
This PR works on refactoring owned tests to add it for borrowed module.
*Changes:*
- Added PartialEq/Eq for `BorrowedSymbolToken`, `BorrowedImportSource`, `BorrowedStruct` and `BorrowedSequence`
- Added `FromIterator` for `BorrowedSequence`
- Added unit tests for borrowed module same as owned tests.
=> Added PartialEq and tests for borrowed module

src/types/type.rs
=> Adds conversion from `ion_c_sys::ION_TYPE` to `IonType`.

ion-c-sys/src/lib.rs
Fixes conversion from Ion C decimals where negative coefficients were being double negated.
=> [ion-c-sys] Fixes double negation for the coefficient of decimals.

ion-c-sys/src/reader.rs
amzn/ion-c#233 triggers an assertion failure when reading an empty LOB,
so we avoid this case explicitly.
=> [ion-c-sys] Short circuits empty case `IonCReader.read_bytes()`.

src/types/timestamp.rs
=> Adds `From<ion_c_sys::timestamp::IonDateTime>` for `Timestamp`.

src/types/timestamp.rs
I merged in some suggested fixes, from #191, but did not apply the changes in the test that used it.
=> Fixes unit test to use `fractional` instead of `frac`.

.github/workflows/coverage.yml
Also changes profile back to minimal.
Now that we're pinning the version, I've noticed that the most recent nightly works.
=> Update codecov to use rust nightly-2021-04-18.

src/value/borrowed.rs, src/value/mod.rs, src/value/owned.rs
*Issue #184*
This PR works on making Element construction generic.
*Changes:*
- Added `From<X>` for `Owned/BorrowedElement` 
- Added a LobBuilder trait which specifies construction of `clob` and `blob` using `into_clob` and `into_blob` respectively.
- Also added `into_list` and `into_sexp` in `Sequence` trait similar to `LobBuilder`.
*Test:*
Modified tests to use `From<X>` of `Owned/BorrowedElement`.
=> adding changes for making `Element` construction generic

.github/workflows/coverage.yml, Cargo.toml, ion-c-sys/Cargo.toml
Updates coverage workflow to nightly-2021-04-21.
=> Version bump for `ion-rs` and `ion-c-sys`.

src/types/magnitude.rs, src/types/timestamp.rs, src/value/loader.rs, src/value/mod.rs
* Fixes lifetimes on `Loader`.
* Cleans up `loader` module documentation a bit.
* Fixes references in `magnitude` and `timestamp` modules.
Fixes #208.
=> Adds doc test example for `Loader` API.

Cargo.toml, src/value/loader.rs, src/value/mod.rs, tests/loader_test_vectors.rs
* Adds `test-generator` create dev dependency to get test per file.
* Adds a test suite with `good`/`bad` files with skip lists.
- `equivs` and `non-equivs` are also supported with
`embedded_document` parsing.
* Adds `Loader::load_all` convenience method.
* Adds doc test example in `loader` module docs and fixes the iterator
example.
Additional notes:
* Added #216 as a result of non-equivs testing and it definitely exposes
a weakness in our unit tests and bug in our `PartialEq` for `...Struct`.
* Added #218 to track a particular set ion-c integration issues around integer
sizes and binary reader.
* Added #219 to track adding support for unknown text symbol tokens in `Loader`.
* Added #220 to track adding `IonEq`.
* Added amzn/ion-c#235 as these tests run into problems with negative
binary …
=> Adds `ion-tests` test file integration for `Loader`.

src/value/loader.rs, src/value/mod.rs, tests/loader_test_vectors.rs
* Adds doc test examples for this API.
* Adds support in the loader integration tests for `load_one`.
Resolves #211.
=> Adds `Loader::load_one` convenience method.

src/types/coefficient.rs, src/types/decimal.rs, src/types/timestamp.rs
Also Makes `TryFrom<Coefficient>` and `TryFrom<BigDecimal>` have
an associated error type be `IonError`.
This provides marginal utility for #209.
Prerequisite for #197.
=> Adds `TryInto<IonDateTime>` for `Timestamp`.

Cargo.toml, ion-hash/Cargo.toml, ion-hash/README.md, ion-hash/src/lib.rs
Not sure we want this to live here forever, but this should let us
iterate in lock step with the in-development ion-rs crate.
=> Scaffold a subcrate for ion-hash

.github/workflows/coverage.yml, Cargo.toml, ion-c-sys/Cargo.toml, ion-hash/Cargo.toml
Updates code coverage for `nightly-2021-04-24`.
=> Updates versions for crates for publishing `ion-hash`.

ion-hash/Cargo.toml
Fixes some meta-data for crates.io:
* Removes a keyword because of the 5 keyword limit on crates.io.
* Updates the keyword slug from `hash` to `cryptography`.
- As per https://crates.io/category_slugs
=> Updates version for `ion-hash`.

.gitmodules, tests/loader_test_vectors.rs
* Removes skip-list for amzn/ion-c#235.
* Updates `ion-c` and `ion-tests` submodules to HEAD.
* Fixes URL in ion-c submodule.
=> Updates `ion-c-sys` to pick up fix for binary literals.

.github/workflows/rust.yml
Doing the recursive delete is really slow sometimes taking up to 10
minutes.  This change just targets the directory with the `libclang.dll`
that is problematic for `bindgen`.
=> Changes the "Remove MSys64" CI Step for Windows.

src/value/borrowed.rs, src/value/mod.rs, src/value/owned.rs
*Issue #204*
This PR works on filling in all `new_...` methods for `Builder` trait created by #199.
*Changes:*
- Added `new_...` method for all types in Builder trait
- Modified tests to use `new_...` method construct element.
*TODO:*
- Add `From<X>` for all types in `Element` trait as defined below:
```rust
trait Element 
where
Self:From<i64> + From<f64> + … {
```
- Add generic test to verify above mentioned element constructions `e1` and `e2`.
=> Filled `Builder` trait with `new_...` methods for all types

.github/codecov.yml
Specifically makes coverage targets fixed, especially given how
unreliable `grcov` seems to be.
Tested with:
`curl --data-binary @.github/codecov.yml https://codecov.io/validate`
=> Adds codecov.yml.

src/lib.rs, src/types/mod.rs, src/value/dumper.rs, src/value/mod.rs, tests/loader_test_vectors.rs
Provides a fixed buffer output implementation using `ion-c-sys`.
This implementation uses very specific `unsafe` code to return
the written data as an output slice.  It has to do this because
`IonCWriterHandle` borrows the input slice to write *implicitly*,
though the lifetime is tracked through the wrapper.
* Adds basic configuration enums.
* Adds constraint for `Builder<SymbolToken = Self::SymbolToken>`
for `Element`.
* Adds `Into<ION_TYPE>` for `IonType`.
* Adds `try_to!` macro to integrate `Option` with `IonResult`
more easily (h/t to @marcbowes in #215)
* Adds an doc test to demonstrate usage in the main module.
* Adds basic unit tests that have expectation on encoded bytes.
* Adds round trip testing for `ion-tests` and `good` tests for various
permutations of loading/dumping values. …
=> Adds the `Dumper` API.

ion-hash/src/lib.rs, ion-hash/tests/ion_hash_tests.rs, src/value/mod.rs, src/value/reader.rs, src/value/writer.rs, tests/element_test_vectors.rs
* Renames the `value::loader` module to `value::reader`.
* Renames the `value::dumper` module to `value::writer`.
* Renames various references to dump/dumper and load/loader.
* Renames `loader_test_vectors.rs` to `element_test_vectors`.
* Minor API cleanup to match the new names.
Fixes #251 and #243.
=> Renames `Loader` and `Dumper to `ElementReader` and `ElementWriter`.

.github/workflows/coverage.yml, Cargo.toml, ion-c-sys/Cargo.toml, ion-hash/Cargo.toml
This gets `ion-rs` ready to publish for new APIs.
Patch level version bump for `ion-hash` and `ion-c-sys`.
Made the dependencies for all crates consistent.  Notably changed the
dependencies to `x.y` format over `x.y.z`.  The rationale for this
change is that we've been a bit rigid on patch versions and that has
caused some downstream compatibility woes.  If any particular crates we
depend on break semver, we can always add the patch version in for those
crates (and/or use tilde versions).
Another change is switching from `^x.y` to just `x.y` as these syntaxes
are the same as per the Cargo book and we had a mixture of both, so I
went with preferring the one that crates.io naturally suggests.
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html
Also updates code coverage …
=> Version bump for all crates to publish.

Cargo.toml, ion-c-sys-macros/Cargo.toml, ion-c-sys-macros/src/lib.rs, ion-c-sys/Cargo.toml, ion-c-sys/src/reader.rs, ion-c-sys/src/result.rs, src/value/reader.rs
Introduce Position, populate in IonCReader
This commit introduces a `Position` type that represents the bytes,
lines and offset into data. Essentially, this mirrors the ion-c
`ion_reader_get_position` API. The `Reader` trait can produce one of
these via a new method, `Reader::pos()`.
A new proc macro `#[position_error]` automatically calls this API if any
of the `Reader` methods fail. The resulting `Position` is stored in
`IonCError::position`.
The motivation behind this commit is quite simple: while working on
ion-hash, the ion_hash_tests.ion sample failed to load. All I got was a
test failure with a `Result` that said "null": not super helpful! No
backtraces, nada. Now, the error includes the exact place where the
Reader produced the Err variant from!
By submitting this pull request, I …
=> Include current reader position in errors

src/value/mod.rs
During review of #239, I found that the text around `SymbolToken`
was a little obtuse and potentially incorrect around `$0`.
Rendered part of the document (as an image--sorry!):
=> Minor cleanup on `SymbolToken` documentation

src/value/borrowed.rs, src/value/mod.rs, src/value/owned.rs, tests/loader_test_vectors.rs
*Issue #216 *
This PR works on solving the issue with symmetry in `Struct` of `Value` API.
*Changes:*
- Added length check in the `PartialEq` of `...Struct` for symmetry.
*Tests:*
Added unittests for different length structs in `Value` API.
=> changed PartialEq for struct for symmetry bug

src/value/borrowed.rs, src/value/mod.rs, src/value/owned.rs, tests/element_test_vectors.rs
This PR works on adding changes for #239 with a rebase.
*Changes:*
* Changed `PartialEq` for owned and borrowed structs.
* Modified `ion-tests` for `Element` round trips to not ignore the symmetry.
* included comment explaining equality in both directions.
* Adds specific tests for testing `Struct` implementations.
=> Fixes `PartialEq` for `Struct`.

ion-hash/src/representation.rs, src/binary/cursor.rs, src/binary/mod.rs, src/binary/uint.rs, src/binary/writer.rs
This commit refactors the code that produces the "magnitude" subfield
out of `BinarySystemWriter`, allowing the code to be re-used in
ion-hash.
The implementation returns a I64Magnitude type rather than a slice. This
avoids an allocation (Vec, for example).
ion-hash now avoids i64 -> BigInt as a result of this change.
-------
=> Refactor out `raw::i64_magnitude`

ion-hash/src/lib.rs, ion-hash/src/representation.rs, ion-hash/src/type_qualifier.rs, ion-hash/tests/ion_hash_tests.rs, src/types/mod.rs
Before this commit, every `Element` visited during ion hash computation
would need to allocate a vector: because each element type can be
represented by a variable number of bytes! For example, a boolean has no
representation while a string is representated by its UTF8 bytes.
This commit fixes that by having the representation implementation write
to the digester directly. For some types (like a BigInt) we will still
need a variable length vector. But in other cases, we now no longer need
to allocate.
While implementing this, I wanted to make the escape method also not
require allocation. This is a simple case of wrapping the `update`
method to maybe write two bytes per byte written. However, because we
were dependent on the `Digest` trait, writing the wrapper required
wrapping all of …
=> Rework ion-hash representations

src/types/timestamp.rs
*Issue #, if available:* #190
Before this commit, `TimestampBuilder.build_at_offset` claimed to take
minutes but actually took "seconds west of UTC". Now, we take "minutes
east of UTC" which is more inline with both intuition (at least, my
own!) and how Ion represents the value in binary.
Note that the `Timestamp` type uses the chrono types internally (such as
an offset in seconds). This creates some annoying multiply/divide by 60.
However, given that Ion doesn't actually support representing offset in
seconds, it feels right to me to use minutes in our API. Maybe, in
future work, we should more clearly restrict offsets to minutes and not
use the chrono type.
-------
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> Clarify TimestampBuilder.build_at_offset

src/binary/decimal.rs, src/binary/mod.rs, src/binary/timestamp.rs, src/binary/writer.rs, src/types/coefficient.rs, src/types/decimal.rs
A very similar story to the recent timestamp extraction, but now for
decimals! Encoding is done off the in-crate `Decimal` type (was:
`BigDecimal`) and avoids allocation where possible.
-------
=> Extract binary decimal encoding to binary/decimal.rs

ion-hash/tests/ion_hash_tests.rs, src/binary/timestamp.rs
*Issue #, if available:* #273
This commit uses the new decimal encoder to encode fractional timestamps
as a decimal. Two timestamp tests that were failing now pass!
-------
=> Use new decimal encoding to fix #274

ion-hash/src/element_hasher.rs, ion-hash/src/lib.rs, ion-hash/src/representation.rs, ion-hash/tests/ion_hash_tests.rs
Before this commit, we were passing around a sink (that implements
digest or write) as a `&mut` "out" parameter. Ugly in general, but even
more so given we had to repeat the `Digest` subtraits over and over.
Now, we have two traits (split simply for code organization). One trait
handles the overall hashing orchestration, while another handles the
representation. Other than some funny business with calling syntax, this
worked out pretty nicely!
Note that I absolutely have _not_ thought through the traits
nicely (i.e. "are we happy with the public/private split?" was not a
consideration). Rather, I focused on the mechanical refactoring to see
if this was worth it. There are loads of doc/comments that don't make
sense anymore that I'll fix up shortly!
------- …
=> Move ion-hash implementation behind traits

.github/workflows/coverage.yml, src/data_source.rs, src/result.rs
Prior to this commit, multiple methods in the IonDataSource trait would
either loop infinitely or return an `IoError` in the event of an
unexpected EOF.
This commit causes all of the methods in question to detect EOFs and
report them as a decoding error. Work needed to add a proper
IonError::IncompleteData enum variant is being tracked in #299.
Fixes #300.
=> Makes IonDataSource report EOF reliably

src/text/writer.rs
This PR adds a `write_timestamp` method alongside the existing
`write_datetime` method, which is now marked deprecated. This
allows users to write an Ion timestamp in textwith full fidelity.
=> Adds a `write_timestamp` method to the text writer

src/binary/cursor.rs, src/binary/timestamp.rs, src/binary/writer.rs, src/types/timestamp.rs
* Adds a `write_timestamp` method to the binary writer alongside
`write_datetime`, which is now deprecated.
* Fixes a bug in `read_timestamp` that caused timestamps with
offsets to constructed incorrectly. Binary Ion encodes each
time unit field in UTC; prior to this patch, the reader would
treat those fields as local time. This required adding a
method to the TimestampBuilder API to allow callers to specify
that their time units were in UTC.
=>  Adds `write_timestamp` to binary writer

examples/read_all_values.rs, src/binary/cursor.rs, src/binary/int.rs, src/cursor.rs
This patch adds a `read_decimal` method to the binary reader
alongside the existing `read_big_decimal` method, which is now
deprecated. Fixes #309.
It also adds an `is_negative` flag to the `Int` encoding primitive,
allowing it to represent negative zero when necessary. Fixes #9.
=>  Adds a `read_decimal` method to the binary reader

src/binary/decimal.rs, src/binary/int.rs, src/binary/var_int.rs, src/binary/writer.rs, src/reader.rs, src/types/decimal.rs
* Adds a `write_decimal` method to the binary writer alongside
the existing `write_big_decimal` method, which is now deprecated.
* Adds a `write_negative_zero` method to the Int encoding primitive.
This method was not needed previously as `BigDecimal` was not
capable of representing -0. Users could not write a decimal -0
prior to this patch.
* Adds an `is_negative_zero` method to the Int encoding primitive,
allowing the binary reader to test for that case.
* Adds an implementation of `TryFrom<f64>` for `Decimal`. This produces
a `Decimal` approximation of the input `f64`'s value (unless the `f64` is
`inf`, `-inf`, or `nan`). It's helpful largely for writing tests.
=>  Adds `write_decimal` method to binary writer

src/text/mod.rs, src/text/parsers/containers.rs, src/text/parsers/mod.rs, src/text/parsers/top_level.rs, src/text/reader.rs, src/text/text_buffer.rs, src/text/text_data_source.rs
This PR allows a `TextReader` to be created from a variety of text
data sources, including `String`, `&str`, `&[u8]`, and `BufReader`.
Support for other types can be addede by implementing the
`TextIonDataSource` trait.
It also introduces the `TextBuffer`, a type which can pull text
into a buffer `n` lines at a time and discard bytes as they're
processed. This enables the reader to process its input in a
streaming fashion, holding a modest amount of data in memory at
a time.
The patch adds parsing logic to detect the beginnings and endings of
the various container types. However, it does not add logic for
stepping into/out of those containers.
Finally, by leveraging the above features, the existing
proto-`TextReader` can now iterate over a text Ion stream containing
multiple top-level …
=> Adds streaming support to the text reader

src/text/mod.rs, src/text/parsers/symbol.rs, src/text/parsers/top_level.rs, src/text/reader.rs
* `parse_symbol` can now match text symbol IDs (e.g. `$23`)
* Symbols read from the stream are now represented as
`OwnedSymbolToken`s instead of `String`s to allow for the case
in which a given symbol's ID was found and the text has not yet
been looked up.
* The reader's `next()` method now returns an `(annotations, item)`
tuple instead of just an `item`. If there are no annotations on
an item, the annotations Vec is empty.
=> Adds support for reading text annotations

src/text/mod.rs, src/text/parsers/comments.rs, src/text/parsers/mod.rs, src/text/parsers/top_level.rs, src/text/reader.rs
This PR defines new parser rules for handling rest-of-line and
multiline comments.
=> Adds comment parsing to the text reader

src/text/mod.rs, src/text/parsers/annotations.rs, src/text/parsers/mod.rs, src/text/parsers/stream_item.rs, src/text/parsers/top_level.rs, src/text/reader.rs
**This PR contains no logic changes, it only reorganizes some of the text parsing functions and their corresponding unit tests.**
* Creates an `annotations` module and relocates the
relevant parser functions to it.
* Moves `top_level_stream_item` unit tests from the
`reader` module to the `stream_item` module.
=> Reorganizes text parsing modules

ion-hash/src/type_qualifier.rs, src/binary/cursor.rs, src/binary/header.rs, src/binary/type_code.rs
*Description of changes:* 
Adds support for NOP padding in the binary cursor, as described in the [binary spec](https://amzn.github.io/ion-docs/docs/binary.html). 
=> Support NOP-padded data

src/lib.rs, tests/reexport.rs, tests/reexport_external.rs
This commit pub-uses bigdecimal so that consumers can use the bigdecimal
type without have explicit exact-version dependency.
bigdecimal is a <1.0 library, and so cargo will pull in additional
copies of it by default, as semver says each release of a <1.0 crate is
backwards incompatible. So, if a consumer of ion-rust didn't have the
exact right version, then the `TryFrom<Decimal> for BigDecimal`
implementation wouldn't be accessible.
Fixes #302
-------
=> reexport bigdecimal

ion-c-sys/Cargo.toml, ion-c-sys/src/lib.rs, ion-c-sys/src/timestamp.rs, src/binary/raw_binary_reader.rs, src/reader.rs, src/symbol_table.rs, src/system_reader.rs, src/types/mod.rs, src/types/timestamp.rs, src/value/borrowed.rs, src/value/owned.rs, src/value/writer.rs
Part of #348.
Incorporates remaining Clippy suggestions. Upgrades `ion-c-sys` dependency on `bindgen` from `0.58` to `0.59.2` to eliminate a number of unnecessary `'static` lifetimes in the `bindgen` output.
After this PR is merged, we'll be able to add `cargo clippy` as a GitHub Action.
=> Clippy suggestions

.github/workflows/rust.yml
Fixes #348.
Adds a GitHub Action to run `cargo clippy` and post any suggestions to the body of the PR as comments.
=> Adds cargo_clippy GitHub Action

ion-c-sys/Cargo.toml
Updates the `ion-c` commit used by `ion-c-sys` and bumps its crate version to v0.4.14.
=> ion-c-sys v0.4.14, updated ion-c

src/binary/raw_binary_reader.rs, src/binary/writer.rs, src/lib.rs, src/raw_symbol_token.rs, src/raw_symbol_token_ref.rs, src/raw_writer.rs, src/text/parsers/float.rs, src/text/parsers/integer.rs, src/text/raw_text_reader.rs, src/text/text_value.rs, src/text/writer.rs, src/types/coefficient.rs, src/types/decimal.rs, src/types/timestamp.rs
This is a large diff, but is largely a reorganization of existing code. I've added my own review comments to highlight places where logic changes have been introduced.
A subsequent PR will create a user-level `Writer` that can wrap any implementation of `RawWriter`, abstracting over text and binary.
-----
This patch introduces a `RawWriter` trait that captures the
format-agnostic encoding functionality needed to write native Rust types
to a stream as Ion values. Unlike the higher-level `Writer` type,
`RawWriter` implementations are not required to manage a symbol table.
Summary of changes:
* Adds the `RawWriter` trait.
* Renames `BinarySystemWriter` to `RawBinaryWriter`.
* Renames `TextWriter` to `RawTextWriter`.
* Provides an impl of `RawWriter` for `RawBinaryWriter` and
`RawTextWriter`. …
=> Introduces the `RawWriter` trait

ion-c-sys/src/writer.rs, src/binary/binary_writer.rs, src/binary/decimal.rs, src/binary/mod.rs, src/binary/raw_binary_writer.rs, src/binary/timestamp.rs, src/lib.rs, src/reader.rs, src/text/mod.rs, src/text/raw_text_writer.rs, src/text/text_writer.rs, src/writer.rs
This PR introduces user-level wrappers for the `RawBinaryWriter`
and the `RawTextWriter`. These higher-level types manage a
symbol table and so can convert between text and symbol IDs,
adding new symbols when appropriate.
This PR also renames the `RawWriter` trait to `Writer`, as the
methods in its interface are applicable to both the raw and user
views of data.
While this PR adds basic unit test for the new wrapper types, it
stops short of providing exhaustive correctness checking. One or
more follow-on PRs will add full integration with ion-tests,
demonstrating spec conformance.
=> Adds user-level `TextWriter` and `BinaryWriter`

Cargo.toml, src/types/coefficient.rs, src/types/decimal.rs, src/types/magnitude.rs
*Issue #363*
This PR works on adding `scale` and `precsion` methods to `Decimal` type.
* adds `number_of_decimal_digits()` to `Magnitude` and `Coefficient`.
* adds `precision()` to `Decimal` types
* adds `scale()` to `Decimal` type
*Tests:*
* adds unit tests in `Decimal` type.
=> adds `scale` and `precision` methods to `Decimal` type

examples/read_all_values.rs, src/binary/binary_writer.rs, src/binary/raw_binary_reader.rs, src/binary/raw_binary_writer.rs, src/raw_reader.rs, src/reader.rs, src/symbol_table.rs, src/system_reader.rs, src/text/raw_text_reader.rs, src/text/text_writer.rs, tests/good_test_vectors.rs
*Issue #, if available:* Fixes #368.
Each implementation of `StreamReader` has an associated type called
`Item` that represents the set of possible entities that the reader may
encounter in its stream:
| Reader       |      Item        |
|--------------|------------------|
| RawReader    | RawStreamItem    |
| SystemReader | SystemStreamItem |
| Reader       | StreamItem       |
While the entities enumerated by `Item` vary according to the reader's
level of abstraction, all of them include a `Value` variant that
indicates that the reader is currently positioned over an Ion value.
Prior to this PR, each `Value` enum variant was modeled as:
Value(IonType, bool)
in which the `IonType` represented the value's corresponding Ion data
type and the `bool` indicated …
=> Null stream item

Cargo.toml, ion-hash/Cargo.toml
*Issue #, if available:* #367
* Bumps `ion-rs` to v0.9.0.
* Bumps `ion-hash` to v0.6.0 and sets its `ion-rs` dependency to v0.9.0
=> Version bump to v0.9.0, update ion-hash dep

src/binary/raw_binary_reader.rs, src/binary/raw_binary_writer.rs, src/reader.rs, src/text/parsers/string.rs, src/text/parsers/text_support.rs, src/text/parsers/timestamp.rs, src/text/raw_text_reader.rs, src/types/decimal.rs, src/types/integer.rs, src/types/magnitude.rs, src/types/timestamp.rs, tests/element_test_vectors.rs
* The `RawBinaryReader` now surfaces an error if it encounters...
* an annotated value whose length doesn't match that of the
annotations wrapper.
* an annotations wrapper with no annotations
* an annotations wrapper with no value
* a negative integer (typecode=3) with a magnitude of 0.
* a malformed IVM.
* an IVM at any depth other than 0.
* a value with with typecode=15. (Previously it panicked.)
* a timestamp with a length <= 1 (missing required fields)
* an empty ordered struct
* The `RawBinaryWriter` now correctly encodes the annotations wrapper
length of annotated containers. Previously the reader would
ignore this (often redundant) field, allowing tests to pass
erroneously. The binary writer would omit the container's header
bytes from its size calculations.
* The `RawTextReader` …
=> Fixes most `bad` native reader tests from `ion-tests`

ion-c-sys/src/result.rs, src/binary/raw_binary_writer.rs, src/binary/uint.rs, src/lib.rs, src/raw_reader.rs, src/stream_reader.rs, src/text/mod.rs, src/types/timestamp.rs, src/writer.rs
Adds `#![deny(rustdoc::broken_intra_doc_links)]` to the crate,
requiring all references in doc comments to be valid before it
will build successfully. Also fixes any existing broken links.
Fixes #362.
=> Makes doc links into build errors

Cargo.toml, ion-hash/Cargo.toml
Version bumps:
* `ion-rs` is now v0.10.0
* `ion-hash` is now v0.0.7 and depends on `ion-rs` v0.10
=> Version bumps: ion-rs to v0.10, ion-hash to v0.0.7

src/binary/decimal.rs, src/binary/int.rs, src/binary/mod.rs, src/binary/raw_binary_reader.rs, src/binary/raw_binary_writer.rs, src/text/parsers/clob.rs, src/text/parsers/decimal.rs, src/text/parsers/mod.rs, src/text/parsers/string.rs, src/text/parsers/symbol.rs, src/text/parsers/text_support.rs, src/text/raw_text_reader.rs, src/text/text_buffer.rs, src/types/magnitude.rs, src/types/mod.rs, src/types/timestamp.rs, src/value/mod.rs, src/value/native_writer.rs, tests/element_test_vectors.rs
This PR makes the following changes:
* A native Rust `ElementWriter` implementation (`NativeElementWriter`)
has been added with basic testing; it is not yet being used in
`ion-tests`.
* ion-tests integration has been refactored to facilitate running
roundtrip tests with either the `IonCSliceElementWriter` or the
`NativeElementWriter` as desired.
* Fixed a bug in the ion-tests integration that caused the ion-c reader
to be used in some tests even when the native reader had been requested.
This change surfaced some additional failing ion-tests that have been
addressed in the changes below.
* The 64-bit size limit on the binary encoding primitive `Int` has been
lifted. This allows Timestamps and Decimals of arbitrary precision to be
read; write support for big `Int`s has not been added yet. …
=> Adds `NativeElementWriter`, string/clob validation, big `DecodedInt`s

ion-hash/src/representation.rs, src/binary/binary_writer.rs, src/binary/raw_binary_writer.rs, src/binary/timestamp.rs, src/binary/uint.rs, src/lib.rs, src/text/parsers/float.rs, src/text/parsers/symbol.rs, src/text/parsers/timestamp.rs, src/text/raw_text_writer.rs, src/text/text_writer.rs, src/types/coefficient.rs, src/types/decimal.rs, src/types/timestamp.rs, src/value/native_writer.rs, src/writer.rs, tests/element_test_vectors.rs
This PR makes the following changes:
* Enables `ion-tests` integration for the `NativeElementWriter`,
the pure-Rust DOM writing API. The `IonCSliceElementWriter` is now only
used when paired with the `IonCElementReader`.
* Adds a `Writer::write_integer` method that can encode an `Integer` of
any size.
* Lifts the size restriction on the `Int` encoding primitive, allowing
`ion-rs` to support `Timestamp`s and `Decimal`s of truly arbitrary
precision when necessary.
* Modifies the `RawTextWriter` to:
* escape literals like `\n` and `\r`
* detect symbols whose text resembles a symbol ID (for example:
`'$99'`) and wrap them in quotes to keep them from being interpreted
after roundtripping
* Removes the `FractionalSeconds` variant of `Precision`, making it more
straightforward to compare …
=> Writer tests; fixes:symbols, timestamps, big Ints

.github/workflows/coverage.yml, Cargo.toml, ion-hash/Cargo.toml, src/lib.rs, src/result.rs, src/types/mod.rs, src/types/timestamp.rs, src/value/ion_c_reader.rs, src/value/ion_c_writer.rs, src/value/mod.rs, src/value/reader.rs, src/value/writer.rs, tests/element_test_vectors.rs
`ion-c-sys` provides bindings to the `ion-c` library, allowing Rust
applications to use `ion-c`'s readers and writers to work with Ion data.
Now that the native Rust readers and writers are passing the `ion-tests`
conformance suite, `ion-c-sys` is no longer mandatory.
This PR introduces a new feature, "ion-c-sys", that allows users to opt
into the functionality and dependencies that come with `ion-c-sys`.
For users that do not require `ion-c-sys`, this eliminates the need to
install a C toolchain on their development machine (cmake, clang, etc).
It also cuts build times and test runtimes by more than half.
=> Makes ion-c-sys an opt-in feature

Cargo.toml, ion-hash/Cargo.toml
Version bumps in preparation for a new release.
=> Version bump: ion-rs v0.11.0, ion-hash v0.0.8

ion-c-sys/Cargo.toml, src/binary/int.rs, src/binary/non_blocking/type_descriptor.rs, src/binary/raw_binary_reader.rs, src/binary/raw_binary_writer.rs, src/binary/uint.rs, src/binary/var_int.rs, src/data_source.rs, src/raw_symbol_token.rs, src/raw_symbol_token_ref.rs, src/reader.rs, src/result.rs, src/text/parent_container.rs, src/text/parsers/decimal.rs, src/text/parsers/integer.rs, src/text/parsers/timestamp.rs, src/text/raw_text_reader.rs, src/text/raw_text_writer.rs, src/types/timestamp.rs
* Commit 1 updates `ion-c-sys`' dependency on `ion-c` to the latest commit on the `master` branch. 
* Commit 2 addresses several (correct) clippy warnings that seem to have been added in Rust 1.62.
This will be the last change before the version bump to `v0.12.0`.
=> Updates ion-c to latest commit, fixes clippy warnings

src/text/text_formatter.rs
Previously, the IonValueFormatter (which is used in the `Display`
impl for the `Element` API) would use commas to delimit child
values in an s-expression. Commas are the delimiter for list values
and struct fields, but s-expressions simply use whitespace.
Following this change, s-expression values are delimited with a
single space.
Fixes #403.
=> The IonValueFormatter now uses the correct s-exp delimiter

src/data_source.rs
* Adding an implementation of `ToIonDataSource` for `std::io::Cursor` for completeness.
* Adding an implementation of `ToIonDataSource` for `&[u8; N]` as an additional acceptable type for any method accepting a `ToIonDataSource`, such as the readers.
* Update the `IonDataSource` trait to have default implementations, since it requires BufRead.
* Update the `ToIonDataSource` to put a trait bound on the `DataSource` associated type of `IonDataSource` instead of `BufRead` which is more specific and correct.
=> Add a ToIonDataSource implementation for std::io::Cursor and references to byte arrays.

src/types/timestamp.rs
This PR works on changes for `Ord` implementation of `Timestamp` to consider both datetime and fractional seconds for comparison.
* considers datetime comparison result as well as fractional seconds
comparison result for `Ord`
* changes `fractional_seconds_equal()` to convert `Option<&Mantissa>` to `&Mantissa`, where default value `Mantissa::Digits(0)` is used for `None`. This guarantees a `fractional_seconds`  value to be present at all times and makes it easier to compare those fractional seconds.
*Test:*
* adds test case for fractional second and year precision timestamps
ordering
=> adds changes for `Ord` implementation of `Timestamp`

.gitignore, Cargo.toml, ion-c-sys/Cargo.toml, ion-c-sys/src/result.rs, ion-c-sys/src/timestamp.rs, ion-hash/Cargo.toml
This Pr adds version bump for `ion-rs` to `v0.13.0` and also adds `.gitignore` change.
=> bumps `ion-rs` version to `v0.13.0`

src/binary/timestamp.rs, src/text/mod.rs
#293 
Use parse_timestamp instead of chrono to parse Timestamp. The expected bytes written were checked against using `ion dump`.
=> Use parse_timestamp instead of chrono to parse Timestamp

src/binary/binary_writer.rs, src/binary/non_blocking/raw_binary_reader.rs, src/raw_symbol_token_ref.rs, src/symbol.rs, src/symbol_table.rs, src/text/raw_text_writer.rs, src/text/text_formatter.rs, src/value/borrowed.rs, src/value/mod.rs, src/value/native_reader.rs, src/value/native_writer.rs, src/value/owned.rs, src/value/reader.rs, tests/element_test_vectors.rs
This patch:
* Adds an `Unknown` variant to the inner representation of 
`Symbol`, allowing it to represent `$0`.
* Removes the `IonImportSource` trait and its implementations.
This type enabled readers to compare symbols in the event that
the corresponding shared symbol table could not be found, a niche
use case. Removing `IonImportSource` eliminates a surprising number
of allocations.
* Updates the `IonSymbolToken` trait. Now that import source is not
being tracked/considered, implementations must update their
behavior for equivalence testing.
* Replaces usages of the `owned::SymbolToken` type with the `Symbol`
type that is used in all of the `IonReader` APIs. The `Symbol` type
takes advantage of `String` interning via the symbol table, which
was still a TODO for `owned::SymbolToken`. …
=> Updates symbol logic in the Element APIs

Cargo.toml, src/value/borrowed.rs, src/value/mod.rs, src/value/owned.rs
*Issue #200*
This PR changes `Struct` and `StructRef` implementations to consider field order
- replaces usage of `HashMap` with `LinkedHashMap`
- adds dependency to `hashlink` in `Cargo.toml`
*Test:*
Added a unit tests in `mod.rs` which tests operations on struct through generic trait `IonElement`.
=> changes `Struct` and `StructRef` implementations to consider field order

src/text/raw_text_writer.rs, src/text/text_formatter.rs, src/types/timestamp.rs
This change fixes GH #434. It moves the (duplicate) Timestamp formatting
logic out of the raw_text_writer and text_formatter and uses it to
implement Display for Timestamp.
In addition to cutting duplicate code, this makes the Timestamp more user
friendly.
There is some back-and-forth between Result and IonResult that I don't love.
It appears to me that one cannot capture any info with Result's Err, so I don't 
think there is something better we can do functionally.
That said: I'm pretty new to rust, so feedback welcome!
=> Implement Display for Timestamp

src/lib.rs, src/symbol_ref.rs, src/value/borrowed.rs, src/value/mod.rs, src/value/owned.rs
This PR works on changes borrowed module to use SymbolRef and simplifies `StructRef`. 
* adds implementation of `Hash`, `From<&str>`, `Borrow<str>` for `SymbolRef`
* makes `SymbolRef` publicly visible in crate
* removes usage of `SymboltokenRef` from borrowed module and instead uses `SymbolRef`
* removes the separate `no_text_values` collection in `StructRef`
* adds `len()` and `is_empty()` for `StructRef`
* adds `IonEq` implmentation for `ElementRef`
* some minor doc comment changes for owned module
*Test:*
- modifies doc test use `SymbolRef` for borrowed module tests
- adds tests for `len` and `is_empty` methods of `StructRef`
=> changes borrowed module to use `SymbolRef` and simplifies `StructRef`

src/text/raw_text_writer.rs, src/text/text_formatter.rs, src/types/integer.rs
This PR works on adding `Display` implementation for `UInteger` and ``Integer`.
*Test:*
Adds unit tests for `Display` of `UInteger` and `Integer`.
=> adds implementaion of `Display` for `UInteger` and `Integer`

Cargo.toml
Bumps the crate version to v0.14.0 in anticipation of another dev release.
=> Version bump to v0.14.0

.github/workflows/coverage.yml, .github/workflows/rust.yml, Cargo.toml, examples/read_all_values.rs, src/binary/int.rs, src/binary/non_blocking/raw_binary_reader.rs, src/binary/raw_binary_reader.rs, src/binary/var_uint.rs, src/symbol_ref.rs, src/value/borrowed.rs, src/value/element_stream_reader.rs, src/value/iterators.rs, src/value/mod.rs, src/value/owned.rs, tests/element_test_vectors.rs
This PR replaces all uses of `Box<dyn Iterator<Item=_> + 'a>` in the `Element` and `ElementRef` APIs with generic associated types. This means that heap allocations are no longer required to iterate over annotations, sequence elements, or struct fields.
Because this change uses generic associated types, it also configures the CI tests to use the `beta` channel of `cargo`. GATs will be available in the next release of Rust (v1.65, out in November); once that happens, we can and should switch back to `stable`. (#443)
This change also removes the recently added dependency on the `linkhash` crate. That dependency was originally pulled in so structs could remember the order in which their fields were inserted for later iteration. However, it only worked if the struct did not contain duplicate …
=> Enables GATs iteration in the Element API

.github/workflows/coverage.yml, .github/workflows/rust.yml, Cargo.toml
*Issue #, if available:* #443
Not a lot to say here- this moves back to `stable` and adds a little documentation in comments.
=> Return to stable Rust now that 1.65 is released

src/catalog.rs, src/lib.rs, src/shared_symbol_table.rs
This PR works on adding implementation of `Catalog`. 
- adds implementation of `SharedSymbolTable`
- adds implementation of `Catalog`
- adds trait `Catalog`, `MutableCatalog`
- adds struct `SimpleCatalog`
*Test:*
- adds unit tests for `Catalog` implementation.
=> adds implementation of `Catalog`

src/text/text_formatter.rs, src/value/owned.rs, tests/element_test_vectors.rs
Fixes #450 
* Added a test based on the "good" test vectors in `ion-tests` to ensure that `Display` is consistent with the default `TextWriter`.
* Fixes the implementation of `Display` for `Element` so that it doesn't try to unwrap `None`.
* Updates `format_struct()`, `format_list()`, and `format_sexp()` to be consistent with the output of a `TextWriter` (I removed some extra whitespace inside the containers), and updates the unit tests accordingly.
=> Stop impl Display for Element from panicking on typed nulls

src/raw_reader.rs, src/reader.rs, src/system_reader.rs, src/text/non_blocking/raw_text_reader.rs, src/text/non_blocking/text_buffer.rs, src/text/raw_text_reader.rs, src/value/native_reader.rs
This PR adapts the blocking `RawTextReader` to act as a blocking wrapper around the non-blocking `RawTextReader`.
The blocking reader uses a non-blocking reader with a `Vec<u8>` backed text buffer, starting with a default size of 4kb. Data is read from the IonDataSource into the text buffer maintaining the 4kb size unless more data is needed in order to parse a larger value, such as a blob.
With each data consuming call, the reader will perform a check if the underlying source has more data, and if the current text buffer has less than 25% data remaining. If so, then the reader will fill the text buffer before calling the consuming function on the non-blocking reader.
If an incomplete error is returned during a consuming call, the …
=> Implement blocking RawTextReader wrapper

.github/workflows/coverage.yml, src/result.rs, src/types/timestamp.rs
* Fix incorrect handling of positive mantissa in fractional seconds for a zero coefficient
* Removes some panics in favor of returning Result::Err
None
While working on fixing up `ion-hash` for the next `ion-rs` release, I discovered some minor issues in the timestamp implementation. This PR fixes them.
* TimestampBuilder will now set fractional seconds to `None` if the fractional seconds coefficient is 0 and the exponent is > -1.
* Added test case for the above change
* Two panics are replaced by returning an EncodingError
* Added `encoding_error` functions that mirror the existing `decoding_error` functions.
* Nightly build for the coverage workflow needed to be updated because the prior nightly build was panicking for my changes …
=> Fix bugs in timestamp

src/binary/int.rs, src/binary/non_blocking/raw_binary_reader.rs, src/binary/raw_binary_reader.rs, src/binary/raw_binary_writer.rs, src/binary/var_int.rs, src/data_source.rs, src/raw_reader.rs, src/reader.rs, src/stream_reader.rs, src/system_reader.rs, src/types/timestamp.rs, src/value/borrowed.rs, src/value/mod.rs, src/value/native_reader.rs, src/value/native_writer.rs, src/value/owned.rs, src/value/reader.rs, src/value/writer.rs, tests/element_test_vectors.rs
None that I'm aware of.
* Fixes broken intra-doc links, some formatting (e.g. Vec\<u8> -> `Vec<u8>` so that `cargo doc` doesn't complain about unclosed HTML tags), and some spelling mistakes.
=> Cleans up broken links in docs

Cargo.toml, ion-hash/Cargo.toml
None
* Version bump to ion-rs v0.15.0; ion-hash v0.1.0
* Update `ion-tests` submodule to the latest commit. "After all the tests pass, why not? Why shouldn't I keep it?", thought I. 
This should be reviewed and merged after #455
=> Version bump to ion-rs v0.15.0; ion-hash v0.1.0

src/binary/non_blocking/raw_binary_reader.rs, src/result.rs, src/text/non_blocking/raw_text_reader.rs, src/text/non_blocking/text_buffer.rs, src/text/raw_text_reader.rs
*Issue #, if available:* N/A
This PR adds a format agnostic Position for error reporting of locations within an Ion document. For both text and binary formats the Position holds a byte offset. Positions within text documents can also add an optional Line and Column to the Position for better error reporting in the text format.
The addition of Position allowed the text only error `IncompleteText` to be removed and the RawTextReader can now use the `Incomplete` error like RawBinaryReader.
This PR also adjusts the handling of incomplete data in the RawBinaryReader's `step_out`. Prior to this PR if `step_out` was called without enough data in the buffer, the function would return `Ok(())` and set the reader's state to `Skipping` with the remaining bytes that could …
=> Format Agnostic RawReader Pass

.github/workflows/rust.yml
*Issue #, if available:* N/A
The clippy-check github action has been failing with the move to the amazon-ion org. This seems to be due to default permissions that changed between the amzn org, and our new org. Documentation seems to say that we should be able to allow write permissions via the workflow config, so this PR is an attempt at doing that.
---
=> Fix permissions for clippy-check

src/raw_reader.rs
None
Looks like two of the format strings for RawStreamItem got transposed at some point. This change swaps them back the way they should be.
=> Fix transposed string formats for RawStreamItem

src/text/non_blocking/text_buffer.rs
*Issue #, if available:* 461
An issue was identified in #461 where a partial unicode sequence was being included in the text returned by the non-blocking text buffer. This turned out to be due to a typo when generating the range of UTF-8 validated characters within the buffer.
In order for `validate_data` to incrementally validate data we keep track of the previously validated end and validate from that point to the current end of the buffer each time more data is added. When the data is passed to `from_utf8` it is sliced from the full data, re-indexing it. In order to account for the re-indexing, we need to add the true offset from the previously validated end, to the new validated end offset returned by `from_utf8`.
Unfortunately prior to this PR a typo/bug was …
=> Fix validated span calculation bug which could result in invalid UTF-8 sequences.

Cargo.toml, ion-hash/Cargo.toml
This patch updates out-of-date dependencies that could be upgraded without any additional logic or code changes.
* `bigdecimal`: 0.2 -> 0.3
* `delegate`: 0.5 -> 0.9
* `num-bigint`: 0.3. -> 0.4
* `rstest`: 0.9 -> 0.16
`pretty-hex` (which was not being used) is no longer a dev dependency.
`base64` and `bytes` remain outdated, but will require logic changes.
=> Dependency updates

src/types/timestamp.rs
Starting in v0.4.23, [`chrono` deprecated a number of methods](https://github.com/chronotope/chrono/pull/827) that would panic if the parameters were out of bounds (e.g. `month=400`) in favor of new versions that would return a `None` if the inputs were bad.
This PR replaces usages of the deprecated methods with their safe counterparts. Unfortunately, the safe counterparts are rather more verbose. However, most of the impacted code was in unit tests.
=> Removes uses of deprecated methods from `chrono`

src/text/parsers/comments.rs
#425
Modifies the comment parser to allow empty comments.
=> Allows empty one-line comments.

tests/element_test_vectors.rs
Fixes #468 
Updates `impl_display_for_element_tests::test_to_string` so that it doesn't return a `Result`. All intermediate results must now be dealt with in this function.
Adds a skip list for failing test cases. All currently skipped tests cases are due to unimplemented functionality.
=> Fix silent test failures caused by unimplemented features

src/types/decimal.rs
Before this all Decimals would be displayed as e.g. 37d-2 instead of 0.37. After this decimals are displayed as `ABC.DEF`, `ABCd3` or `0.000ABC` unless the number of padding zeroes grows large, in which case it will fall back to `A.BCd-E` for some exponent.
This also prefers to quantify the scale of larger numbers, e.g. `ABCDEFGd0` will be written as A.BCDEFGd6 instead of `ABCDEFG.`
"large" is henceforth "six" until someone changes it ;)
=> Make Display for Decimal more human-friendly

src/value/element_stream_reader.rs
This PR suppresses an invalid `clippy` warning.
See issue #472 for details.
=> Suppresses invalid clippy warning

src/text/non_blocking/raw_text_reader.rs, src/text/raw_text_reader.rs
Previous implementation of the non-blocking reader, and its blocking wrapper, had two bugs when handling incomplete errors, and continuing after an incomplete error.
The non-blocking reader did not take into account the `step_out` nesting when unsetting the `need_continue`. When stepping out of a container that contained a container that had not yet been read, this would result in the reader stepping out beyond the target depth.
The blocking reader did not properly mark the stream as complete when stepping out of a container. If a `step_out` caused the last remaining data from the stream to be read (completing the stream) root level values at the end of the stream could be ambiguous and continue to cause incomplete data errors, until …
=> Address boundary handling issues in non-blocking raw text reader, and its blocking wrapper

src/binary/non_blocking/raw_binary_reader.rs, src/binary/non_blocking/type_descriptor.rs, src/element/owned.rs, src/lib.rs
Provides examples for creating, reading, and writing `Element`s.
=> Adds basic crate-level documentation

src/element/mod.rs, src/symbol.rs, src/symbol_table.rs, src/system_reader.rs, src/text/raw_text_writer.rs
This PR modifies the `Symbol` type to use `Arc<str>` instead of `Rc<str>` when sharing references to text, eliminating the last remaining use of a non-`Send` type (`Rc`) in the `Element` API.
Following this change, `Element`s can be sent between threads or shared using native mechanisms like `Arc<Element>`.
Changes:
* Modifies the `Symbol::Shared` enum variant to use `Arc<str>` instead of `Rc<str>`.
* Adds a unit test demonstrating that `Element` implements `Send` and safeguarding against future changes that accidentally violate that property.
* Addresses a `clippy` warning added in Rust 1.70 nightly about using struct builder syntax unnecessarily.
=> Make `Element` implement `Send`

src/element/builders.rs, src/element/list.rs, src/element/mod.rs, src/element/owned.rs, src/element/sequence.rs, src/element/sexp.rs, src/element/struct.rs, src/element/writer.rs, src/lib.rs, tests/element_test_vectors.rs
This PR adds implementations of `IntoIterator` for each of the container `Element` types, allowing the expected looping syntax:
```rust
for element in &list {
// ...
}
for element in &sexp {
// ...
}
for (field_name, value) in &struct_ {
// ...
}
```
It also moves the container types to their own modules for easier navigation.
Each commit is self-contained. Only the final commit (`Implements IntoIterator...`) contains any new logic. The rest are mechanical refactorings. I recommend reviewing them in order.
=> Implements `IntoIterator` for container Elements

src/binary/non_blocking/raw_binary_reader.rs, src/binary/raw_binary_reader.rs, src/element/element_stream_reader.rs, src/element/mod.rs, src/lib.rs, src/raw_reader.rs, src/reader.rs, src/stream_reader.rs, src/system_reader.rs, src/text/non_blocking/raw_text_reader.rs, src/text/raw_text_reader.rs, src/types/mod.rs, src/types/string.rs
This PR introduces a new `Str` type that replaces all usages of
Rust's owned `String` type in the `Reader` and `Element` APIs.
For the time being, the `Str` type is a simple opaque wrapper
around `String` with trait implementations that allow it to be
used in much the same way. Having an opaque wrapper will allow
us to swap out the implementation later without a breaking
change, enabling us to provide stack-allocated small strings,
shared strings (interning), etc as desired.
The name `Str` was selected to:
1. Avoid collisions with `String` and `&str`.
2. Use (an abbreviation of) the same type name as Ion itself (vs, say, `Text`)
We can add more trait implementations and method pass-throughs
as needed.
By submitting this pull request, I confirm that my contribution is made under the terms …
=> Custom string type

src/element/builders.rs, src/element/list.rs, src/element/mod.rs, src/element/sequence.rs, src/element/sexp.rs, src/element/writer.rs, src/ion_hash/representation.rs, src/lib.rs, src/text/text_formatter.rs, tests/element_test_vectors.rs
See issue #500 for discussion.
This PR removes the `IonSequence` trait and reintroduces a concrete `Sequence` type. It also converts `List` and `SExp` into tuple structs that wrap `Sequence`.
`ListBuilder` and `SExpBuilder` have also been removed in favor of a single `SequenceBuilder` implementation with `build_list()` and `build_sexp()` methods.
`List` and `SExp` each implement `Deref<Target=Sequence>`, allowing them both to expose the functionality of their underlying `Sequence` of elements transparently.
This eliminates a fair amount of boilerplate code that was needed to provide functionality for both types. It also enables unified handling for `List` and `SExp` in match expressions in situations where the author does not care about the Ion type distinction. Finally, users no longer …
=> Makes `List` and `SExp` thin wrappers around `Sequence`

src/element/list.rs, src/element/mod.rs, src/element/reader.rs, src/element/sequence.rs, src/element/sexp.rs, src/ion_hash/representation.rs, src/ion_hash/type_qualifier.rs, src/text/text_formatter.rs
This PR partially addresses issue #500.
It modifies the `Value` enum's `List` and `SExp` variants from:
```rust
enum Value {
// ...
List(List),
SExp(SExp),
// ...
}
```
to
```rust
enum Value {
// ...
List(Sequence),
SExp(Sequence),
}
```
while also preserving the standalone `element::List(Sequence)` and `element::SExp(Sequence)` types, which are used primarily by the SequenceBuilder, `ion_list!`, and `ion_sexp!`.
Following this change, matching sequence types is flattened/simplified:
```rust
if let List(seq) | SExp(seq) = value {
// iterate over `seq`
}
```
but we retain the ability to construct strongly typed standalone values when necessary, such as in the `ion_list!`
and `ion_sexp!` macros.
```rust
// Constructs an element::List(Sequence)
let list: List = ion_list![1, 2, 3];
// …
```
=> Makes `Value::List` and `Value::SExp` wrap `Sequence`

src/text/non_blocking/raw_text_reader.rs, src/text/non_blocking/text_buffer.rs, src/text/parsers/text_support.rs
*Issue #, if available:* #494
This PR adds two changes:
1) Updates error handling while parsing escaped string sequences in order to bubble up nom's Incomplete errors to the reader, so that they can be communicated further.
2) Updates `read_from` to ensure that the amount of data read is limited to the length provided by the caller. Prior to this PR the entire rest of the buffer would be used for reading data. While this could be beneficial (the memory is allocated, using it makes sense) the caller expects to read no more than `length`, so as a matter of correctness we shouldn't read more than `length`.
A regression test was also added to mimic the behavior seen in #494.
---
By submitting this pull request, I confirm that my contribution is made under the terms …
=> Handle incomplete errors when parsing escaped string sequences

examples/read_all_values.rs, src/binary/non_blocking/raw_binary_reader.rs, src/blocking_reader.rs, src/element/element_stream_reader.rs, src/raw_reader.rs, src/reader.rs, src/stream_reader.rs, src/system_reader.rs, src/text/non_blocking/raw_text_reader.rs
*Issue #, if available:* #335
This PR removes the `map_`-style functions from the reader trait and replaces their use with `read_`-style functions.
`read_str` was added to the IonReader trait. The function already existed in the binary reader, so it was moved into the trait impl and the implemented for the other readers.
---
=> Remove map_<type> APIs and replace them with read_<type>

src/reader.rs
This makes it consistent with `RawStreamItem` and `SystemStreamItem`.
When writing #512, I noticed that `StreamItem` did not derive these traits.
=> Adds Copy/Clone derivation to StreamItem

Cargo.toml
Version bump in anticipation of the v0.17.0 dev release.
=> Version bump to v0.17.0

.github/workflows/rust.yml, src/binary/header.rs, src/binary/non_blocking/binary_buffer.rs, src/binary/non_blocking/raw_binary_reader.rs, src/element/annotations.rs, src/element/reader.rs, src/element/struct.rs, src/ion_hash/element_hasher.rs, src/ion_hash/mod.rs, src/ion_hash/representation.rs, src/ion_hash/type_qualifier.rs, src/lib.rs, src/raw_reader.rs, src/raw_symbol_token.rs, src/shared_symbol_table.rs, src/text/non_blocking/raw_text_reader.rs, src/text/non_blocking/text_buffer.rs, src/text/parse_result.rs, src/text/parsers/clob.rs, src/text/parsers/containers.rs, src/text/parsers/text_support.rs, src/text/parsers/top_level.rs, src/types/timestamp.rs
Cleans up doc comments such that `cargo doc --document-private-items --all-features` works and is in CI.
Fixes #516
=> Fix rustdoc

src/text/raw_text_writer.rs
*Issue #, if available:* None. 
*Description of changes:* This is the same indentation that `jq` uses by default for prettifying JSON, which makes like-for-like comparisons easiest. An indentation level of 4 also gets deep twice as fast as 2.
Please feel free to discard this pull request if it's unwanted, consider it opening the conversation of "what kind of indentation should we use?"
I intend to add an `--indent` option such as the one that [`jq`](https://stedolan.github.io/jq/manual/) supports to [`ion-cli`](https://github.com/amazon-ion/ion-cli/), but I am here moving the default for `pretty`. 
=> Reduce 'pretty' indentation 4=>2

Cargo.toml, src/lib.rs, src/thunk.rs
Adds `thunk::Thunk` as an experimental API for modeling lazy/eager values that are fallible (and thus evaluate to an `IonResult`. The API supports controlling how the value is materialized from a closure and supports moving values into and out of it.
The `Thunk` models three distinct states:
* ***Deferred***: value is backed by a closure.
* ***Materialized***: value is stored directly in the `Thunk`.
* ***Error***: there was some error evaluating the *deferred* value. This state can be thought of as a deferred value that can *never* be evaluated.
This also backs this API with a Cargo feature called "experimental" that we can use for other such APIs.
resolves: #519, #521
Prerequisite for #520.
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> Adds Lazy Evaluation Support

.github/workflows/rust.yml, src/ion_data/mod.rs, src/ion_hash/mod.rs, src/lib.rs
This change makes it so we build our crate with all the various interesting permutations:
* *default* - build with no features set.
* `--all-features` - build with all the bells and whistles.
* `--features X` where `X` is:
* `ion-hash`
* `experimental`
* `ion-hash,experimental`
When building/testing with these permutations, it uncovered a bug in the `ion-hash` doc tests where the test code depends on an optional feature. This has been conditionally compiled out, preserving the text of the doc comment (only runs when the appropriate feature flag is enabled).
Also updates the build of API docs to error out on leaking internal references.  This change cleans up such documentation comments.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> Adds CI matrix for crate features

src/ion_hash/mod.rs
When compiling only ion-hash with no `sha2` feature, we get a warning that we import an unused `digest::Output`, this gates that import on the feature being enabled.
=> Fixes a warning for ion-hash

.github/workflows/rust.yml, src/ion_data/ion_ord.rs, src/thunk.rs
Made clippy required for CI--we tend to keep the source tree clean, but the clippy warnings are easy to miss and cannot be seen on PRs from user forks.  by adding `-Dwarnings` to the clippy CI step, we make sure this breaks the build--we can always add annotations to ignore suggestions explicitly and/or we can back this out if clippy is too annoying.
Also adds `--workspace` to the clippy, as it doesn't seem to check `ion-hash` by default without it.
=> Fixes clippy warnings

.github/workflows/coverage.yml
This change finally gets us to using ***stable*** rust to generate our code coverage!  Prior to this change, we had to pin to nightly Rust, which was a paper cut whenever that broke for various reasons.
LLVM source coverage in Rust is not perfect (e.g., https://github.com/rust-lang/rust/issues/79649, https://github.com/rust-lang/rust/issues/79417), and Codecov has some of its own issues (e.g., https://github.com/taiki-e/cargo-llvm-cov/pull/255#issuecomment-1513318191), but I believe these to be acceptable compromises to getting off of nightly.
----
Removes pin to nightly and removes the old `-Zprofile` runs and `grcov` based coverage generation in favor of `-C source-instrumentation` which is in stable.
This updates the CI to install `llvm-tools-preview` from `rustup` and install a nice …
=> Updates code coverage CI to stable

README.md, clean-rebuild.sh
The original text suggested using `--all-targets` for building.  This replaces that with `--all-features` as the suggestion for both building and testing.  Removing `--all-targets`, especially for tests, is good because doc tests don't get built/run with that parameter.
Also adds a `clean-rebuild.sh` script to do a bunch of things that one might want to do before a PR (or just sanity check for all the things we care about in CI).  Does not cover all the permutations of features for building, but default and `--all-features`.
=> Updates README

Cargo.toml
This feature, enabled by default in chrono versions <5, includes a dependency on the deprecated time@0.1.x. A security advisory is issued for this verion of time.
Some details available here: https://github.com/chronotope/chrono/issues/602
The `oldtime` feature does not appear to be used by this crate. I verified tests pass locally for me. I hope you will consider merging this change, and thank your for your work on this project!
=> Disable the "oldtime" feature of chrono

src/binary/non_blocking/binary_buffer.rs, src/binary/non_blocking/raw_binary_reader.rs, src/blocking_reader.rs, src/raw_reader.rs, src/text/non_blocking/raw_text_reader.rs
- Fixes an issue where `read_from` would read fewer bytes than it was expected to.
- Addded incomplete guard to an annotation consume that could cause an error when the buffer did not have enough data.
- Fixed an issue where bytes read into a NBR were counted twice when determining if all data had been read. This probably wasn't an issue since `read_from` reads all of the data requested.
- Implements stream completion for non-blocking binary reader.
- Moves Expandable to the raw_reader module now that the binary raw reader is using it.
---
=> Fix multiple blocking binary reader issues

src/types/coefficient.rs, src/types/decimal.rs
Currently, `TryFrom<f64> for Decimal` unconditionally casts the `f64` coefficient to an `i64`, effectively clamping values larger than `i64::MAX` to `i64::MAX`.
This introduces an alternative code path for values larger than `i64::MAX` to create the `Coefficient` through a `BigInt`.
---
=> Fix conversion to Decimal from f64 for values greater than +/- i64::MAX and smaller than +/- 1e-15

Cargo.toml, src/system_reader.rs
While upgrading the `ion-cli` to use `ion-rs` v0.18.0 (see amazon-ion/ion-cli#52), I noticed that the `SystemReader` required a very specific configuration in order to access the raw bytes of the underlying stream. In particular, it required a `BlockingRawBinaryReader` to be the underlying raw reader. Unfortunately, using the raw bytes accessors in that configuration would access the ~4KB internal buffer of the blocking reader, causing a panic once you tried to access data beyond the first 4KB. This patch addresses that problem and bumps the version to 0.18.1 so the fix can be accessed by the `ion-cli`.
=> Hotfix v0.18.1: Exposes raw bytes accessors in the `SystemReader`

src/reader.rs, src/system_reader.rs
The `UserReader` (alias: `Reader`) is implemented as a `(RawReader, SymbolTable)` pair. If/when the `RawReader` encounters a symbol table, the `Reader` consumes it and adds its symbols to the `SymbolTable`.
The `SystemReader` is a very similar; it is also a `(RawReader, SymbolTable)` pair. However, when the `RawReader` encounters a symbol table, the `SystemReader` cannot consume it. Instead, it needs to process _only_ the value over which the `RawReader` is currently positioned. This requires some complex state tracking, but it allows the `SystemReader` to expose/return system-level values while also processing them.
This PR modifies the `UserReader` to be a thin wrapper around the `SystemReader`. Whenever the `SystemReader` reports one or more system-level values, the `UserReader` skips …
=> [User]Reader wraps SystemReader, not RawReader

src/binary/decimal.rs, src/binary/non_blocking/binary_buffer.rs, src/binary/uint.rs, src/lazy/binary/immutable_buffer.rs, src/text/parsers/decimal.rs, src/types/coefficient.rs, src/types/decimal.rs, src/types/integer.rs, src/types/mod.rs, src/types/timestamp.rs
Prior to this patch, `UInt` was an enum offering two storage
options: `u64` and `BigUint`.
This patch wraps that enum (now a private type called `UIntData`) in
an opaque struct, giving us the ability to change that representation
in the future without a breaking change.
This also provides a `TryFrom<&UInt>` implementation for all primitive
integer types.
Related to #507.
A follow-on PR will make the same change for the signed `Int` type.
=> Makes `UInt` an opaque struct type

src/binary/int.rs, src/binary/non_blocking/binary_buffer.rs, src/binary/uint.rs, src/lazy/binary/immutable_buffer.rs, src/types/coefficient.rs, src/types/integer.rs
Fixes #569.
* Signed integer primitives now implement `TryInto<UInt>` and fail if they are negative.
* `Coefficient::new` now takes `I: Into<Magnitude>` where `Magnitude` is a wrapper that signed integers infallibly convert to via absolute value.
=> Signed type impls of Into<UInt> are now fallible

src/binary/int.rs, src/binary/non_blocking/binary_buffer.rs, src/binary/non_blocking/raw_binary_reader.rs, src/binary/raw_binary_writer.rs, src/binary/uint.rs, src/element/element_stream_reader.rs, src/element/element_stream_writer.rs, src/element/mod.rs, src/element/reader.rs, src/ion_hash/representation.rs, src/ion_hash/type_qualifier.rs, src/lazy/binary/immutable_buffer.rs, src/lazy/binary/raw/lazy_raw_value.rs, src/lazy/value_ref.rs, src/stream_reader.rs, src/text/non_blocking/raw_text_reader.rs, src/text/parsers/containers.rs, src/text/parsers/integer.rs, src/text/parsers/top_level.rs, src/text/text_formatter.rs, src/types/integer.rs
The `Int` enum has been renamed to `IntData` and is now `pub(crate)`. 
A new opaque struct type called `Int` now wraps it.
Part of issue #507, related to merged PR #568. 
=> Makes `Int` an opaque struct

src/element/builders.rs, src/element/iterators.rs, src/element/mod.rs, src/element/reader.rs, src/types/list.rs, src/types/sequence.rs, src/types/sexp.rs, tests/element_test_vectors.rs, tests/ion_hash_tests.rs
APIs that returned `Vec<Element>` now return a `Sequence` instead. This allows us to change the storage type without a breaking change. It also means that you can trivially construct a `List` or `SExp` from the output of `Element::read_all`.
This also renames `ElementsIterator` to `SequenceIterator` to avoid confusion with the similarly named `ElementIterator`.
=> Replaces `Vec<Element>` with `Sequence`

src/element/mod.rs, src/types/integer.rs
Adds a blanket implementation of `Into<Value>` for all integer types, which allows them to transitively benefit from the `Into<Element>` implementation that exists for `T: Into<Element>`.
Fixes #573.
=> Adds Into<Value>, Into<Element> impl for all ints

src/element/writer.rs
None
Adds a `write_value(&self, value: &Value)` function to `ElementWriter` so that if you have a `&Value` you don't need to take ownership and convert to `Element` in order to easily write the value.
E.g.:
```rust
fn foo<W: IonWriter>(value: &Value, writer: &mut W) {
// Instead of this:
writer.write_element(&value.to_owned().into());
// Now we can write this:
writer.write_value(value);
}
```
While I was at it, I also updated the documentation for `write_element` and `write_elements`, which can be used at any level, not just for top-level values.
=> Adds write_value to ElementWriter

src/binary/int.rs, src/binary/non_blocking/raw_binary_reader.rs, src/binary/uint.rs, src/binary/var_int.rs, src/binary/var_uint.rs, src/blocking_reader.rs, src/data_source.rs, src/element/mod.rs, src/lib.rs, src/reader.rs, src/tokens/reader_stream.rs
The original implementation of the binary reader used a trait called `IonDataSource` that provided extension methods for implementations of `BufRead`. The binary reader was later rewritten to use a type called `BinaryBuffer`, but `IonDataSource` and its methods were never removed.
This PR removes `IonDataSource` and the vestigial implementations of `read()` for various encoding primitives that relied upon `IonDataSource`.
Finally, it renames the single-method trait `ToIonDataSource` (which suggested types could be converted to an `IonDataSource`) to `IonDataSource`, reclaiming the name for a better use.
=> Removes `IonDataSource` and vestigial `read()` impls

src/types/coefficient.rs, src/types/decimal.rs
=> Adds `From<Int> and `From<UInt>` impls for Decimal

src/lib.rs, src/types/decimal/coefficient.rs, src/types/decimal/magnitude.rs, src/types/decimal/mod.rs, src/types/integer.rs, src/types/mod.rs
This PR:
* Makes `Coefficient` a publicly visible type.
* Adds a `Decimal::coefficient` method to access the coefficient.
* Adds a `Decimal::exponent` method to access the exponent.
* Makes the `decimal` module a directory instead of a flat file
* Moves the `Magnitude` newtype to its own module
* Conversions to/from `Int`, `UInt`, and `Decimal` now return `IonError` instead of `()` in the event of a failure.
Fixes #405.
=> Adds Decimal methods to access the coefficient and exponent

src/binary/decimal.rs, src/binary/int.rs, src/element/writer.rs, src/lib.rs, src/text/parsers/decimal.rs, src/types/decimal/coefficient.rs, src/types/decimal/mod.rs, src/types/mod.rs, src/types/timestamp.rs
Removes the re-export of `Sign` and `Coefficient` from the crate root. They can still be accessed at: `ion_rs::decimal::coefficient::{Coefficient, Sign}`.
Fixes #586.
=> Removes Coefficient and Sign from the root

src/catalog.rs, src/element/builders.rs, src/element/reader.rs, src/element/sequence.rs, src/result/decoding_error.rs, src/result/encoding_error.rs, src/result/illegal_operation.rs, src/result/mod.rs, src/text/parsers/string.rs, src/tokens/reader_stream.rs, src/types/timestamp.rs
Prior to this patch, error structs like `DecodingError` each held a `String`, which meant that if a caller passed in a static string literal, it would always be unnecessarily copied to the heap.
This PR modifies each type and their corresponding constructors in the `IonFailure` trait to operate in terms of `Cow<'static, str>` and `Into<Cow<'static, str>>`, allowing static strings to avoid cloning while still supporting more complex error `String`s constructed with `format!` and the like.
=> Error types now hold a Cow<str> instead of requiring a String

src/binary/binary_writer.rs, src/lib.rs, src/symbol_table.rs, src/system_reader.rs, src/text/text_writer.rs
Removes the `SymbolTable` and `Catalog`/`MapCatalog` types from the public API. Also marks any mutating methods on `SymbolTable` as `pub(crate)`; users do not need to modify the symbol table.
=> Removes `SymbolTable` and `Catalog` from the public API

src/result/decoding_error.rs, src/result/encoding_error.rs, src/result/illegal_operation.rs, src/result/incomplete.rs, src/result/io_error.rs, src/result/mod.rs, src/types/decimal/coefficient.rs, src/types/decimal/mod.rs
Adds doc comments to:
* The `decimal` module
* The `decimal::coefficient` module
* The `result` module and its nested error types
Fixes #587. 
=> Result doc comments

Cargo.toml
Bumps the crate version from `0.18.1` to `1.0.0-rc.1`, the first release candidate for v1.0.0.
=> Version bump to 1.0.0-rc.1

src/types/integer.rs
This PR fixes comparison for cross representation between i64 and BigInt which is used in Ordering implementation of Int.
=> Fix comparison for cross representations in `Int`

src/lazy/any_encoding.rs, src/lazy/binary/raw/reader.rs, src/lazy/binary/raw/sequence.rs, src/lazy/binary/raw/struct.rs, src/lazy/binary/raw/value.rs, src/lazy/decoder.rs, src/lazy/encoding.rs, src/lazy/raw_stream_item.rs, src/lazy/reader.rs, src/lazy/sequence.rs, src/lazy/struct.rs, src/lazy/system_reader.rs, src/lazy/text/buffer.rs, src/lazy/text/encoded_value.rs, src/lazy/text/raw/mod.rs, src/lazy/text/raw/reader.rs, src/lazy/text/raw/sequence.rs, src/lazy/text/raw/struct.rs, src/lazy/text/raw/v1_1/mod.rs, src/lazy/text/raw/v1_1/reader.rs, src/lazy/text/value.rs, src/lazy/value.rs
This PR makes superficial changes that affect a large number of lines of code:
* It stubs out the types necessary to introduce a raw text Ion 1.1 reader, providing those stub types with minimal implementations that forward calls to the existing 1.0 types/implementations. These types will be replaced by actual 1.1 implementations in subsequent PRs.
* It splits the `TextEncoding` type into `TextEncoding_1_0` and `TextEncoding_1_1`
* It renames `BinaryEncoding` to `BinaryEncoding_1_0` to make way for an eventual `BinaryEncoding_1_1`.
This PR contains no logic changes.
=> Stub out types for RawTextReader_1_1

.github/workflows/miri.yml, Cargo.toml, src/lib.rs, src/result/mod.rs, src/serde/de.rs, src/serde/decimal.rs, src/serde/mod.rs, src/serde/ser.rs, src/serde/timestamp.rs
*Related PR: #402*
This PR continues on a [previous PR](#402) to implement `serde` for `ion-rs` and adds an experimental `serde` feature. 
* adds serde module which defines `ser` (serialization) and `de` (deserialization) for Ion data model.
* adds `timestamp` which is a special case for `serde` since serde data model doesn't support Ion timestamps, we use `newtype_struct` to serialize and deserialize timestamps.
* adds `timestamp` which is a special case for `serde` since serde data model doesn't support Ion timestamps, we use `newtype_struct` to serialize and deserialize timestamps.
=> Adds experimental serde feature

benches/read_many_structs.rs, src/lazy/expanded/compiler.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/mod.rs, src/lazy/expanded/sequence.rs, src/lazy/expanded/struct.rs, src/lazy/expanded/template.rs, src/lazy/struct.rs, src/lazy/system_reader.rs
#672 
This PR modifies the `TemplateCompiler` to maintain a `field_name` => `field_value_addresses` index for each template struct that it encounters. This allows `LazyStruct::find(name: &str)` to perform a single `HashMap` lookup any time its backing data is a template. If its backing data is a value literal, it will still need to perform a linear scan.
Commit guide:
* f986c14183f8b3948a58912abef5c9358af16374 contains the meat of the change
* 576fb0b984cf99e7a26f2081149efc7938150423 removes a now-superflous `context` parameter from a few `MacroEvaluator` methods; `MacroEvaluator` stores its own `context` that can be used instead as needed.
* 91f2d25871190a73f6e2fa4409c1685af10d435c Incorporates clippy suggestions
Here are some timings …
=> Constant time struct field access

benches/read_many_structs.rs, src/lazy/binary/immutable_buffer.rs
Optimizes reading `VarUInt`s that are 1 or 2 bytes long. Also adds a binary 1.0 flavor of the existing `read_many_structs` benchmark.
| Benchmark | Before | After |
|:----|:---:| :---:|
| Binary 1.0/scan all | 843.74 us | 776.22 us |
| Binary 1.0/read all | 16.366 ms | 15.391 ms | 
=> Varuint optimization

src/lazy/encoder/mod.rs
* Introduces a `TextContainerWriter_1_0` that houses information and behavior common to the container writer.
* Adds an s-expression writer, `TextSExpWriter_1_0`.
* Adds a struct writer, `TextStructWriter_1_0`.
=> Adds sexp and struct writers to the `LazyRawTextWriter_1_0`

src/types/symbol.rs
*Issue #610*
This PR adds test for`PartialEq` of `Symbol` for `&str`.
=> Adds test for `PartialEq` of `Symbol` for `&str`

src/binary/non_blocking/raw_binary_reader.rs
Currently, the reader will fail if an IVM is encountered following a NOP pad at the top level. This patch fixes that.
=> Fix to support finding an IVM after a NOP in binary v1.0

src/lazy/encoder/binary/v1_1/flex_uint.rs, src/lazy/encoder/binary/v1_1/value_writer.rs, src/types/timestamp.rs
While this diff looks big, some ~900 of the ~1,200 lines are just generously spaced/commented unit tests.
=> Implements writing v1.1 timestamps

src/lazy/binary/raw/reader.rs
#706 fixed the raw binary reader (which is used in the `ion-cli` and `Element` API) to allow it to recognize an IVM following a NOP pad. This PR makes the same change but for the lazy binary reader that will eventually replace the existing reader.
=> Fixes ivm-after-nop in the lazy reader

src/lib.rs, src/symbol_table.rs, src/system_reader.rs
*Issue:*
The issue is in importing shared symbol import. SST import used `RawSymbolToken#text()` method to get a field name of SST import which resulted in not loading the symbol table import properly. `RawSymbolToken#text()` returns `None` if the token is an SID. Instead it should look up in the symbol table to get that SID's text. 
Another issue was with importing a system symbol with a shared symbol table import. While reading Ion data it should add this system table again to current symbol table and but while writing it should return the smallest SID(the system SID). 
This PR works on fixing a bug in shared symbol table import.
* Modified how SST import read symbol text so that in case of SID it
gets corresponding text first
* Modified …
=> Fixes bug in reading shared symbol table import

src/binary/binary_writer.rs, src/binary/raw_binary_writer.rs, src/element/element_stream_writer.rs, src/ion_writer.rs, src/text/raw_text_writer.rs, src/text/text_writer.rs
*Issue #713*
This PR adds a `finish` API to `IonWriter` which flushes the buffered data and returns writer's output.
*Test:*
Added unit tests for `finish` API for binary and text writer. 
=> Adds implementation of `finish` for `IonWriter`

.github/workflows/rust.yml
Fixes #104
Adds Amazon Linux on Aarch64 and x86_64 for workflows that run in the `amazon-ion/ion-rust` (but not for forks).
=> Adds Amazon Linux (arm64 and x86_64) to the build matrix

Cargo.toml, benches/encoding_primitives.rs, benches/write_many_structs.rs, examples/write_log_events.rs, src/element/mod.rs, src/lazy/encoder/binary/v1_0/container_writers.rs, src/lazy/encoder/binary/v1_0/value_writer.rs, src/lazy/encoder/binary/v1_0/writer.rs, src/lazy/encoder/binary/v1_1/container_writers.rs, src/lazy/encoder/binary/v1_1/flex_int.rs, src/lazy/encoder/binary/v1_1/flex_sym.rs, src/lazy/encoder/binary/v1_1/flex_uint.rs, src/lazy/encoder/binary/v1_1/mod.rs, src/lazy/encoder/binary/v1_1/value_writer.rs, src/lazy/encoder/binary/v1_1/writer.rs, src/lazy/encoder/mod.rs, src/lazy/encoder/text/mod.rs, src/lazy/encoder/text/value_writer.rs, src/lazy/encoder/value_writer.rs, src/lazy/encoder/write_as_ion.rs, src/lazy/never.rs, src/lazy/text/raw/v1_1/reader.rs, src/reader.rs, src/result/encoding_error.rs, src/result/io_error.rs
Adds write support for e-expressions in the binary writer.
Additionally:
* Adds a `write_many_structs` benchmark that compares time to write structs in Ion 1.0, Ion 1.1 w/length prefixes, Ion 1.1 w/delimited containers, and Ion 1.1 w/macros.
* Adds an example program that generates a large number of Log4J-style event structs and serializes them in various forms.
* Amends some binary encoding details that were ambiguous in the spec.
* Adds [`ice_code`](https://github.com/zslayton/ice_code/) as a dependency to label cold code paths without having to construct new methods.
* Sets some default allocation sizes for encoding buffers and the bump allocator itself to reduce reallocations.
* Adds a `delegate_value_writer_to!` macro that cuts the number of places the `ValueWriter` trait method …
=> Implements writing e-expressions in binary 1.1

Cargo.toml, benches/read_many_structs.rs, src/data_source.rs, src/element/mod.rs, src/lazy/any_encoding.rs, src/lazy/binary/encoded_value.rs, src/lazy/binary/immutable_buffer.rs, src/lazy/binary/raw/reader.rs, src/lazy/binary/raw/value.rs, src/lazy/decoder.rs, src/lazy/encoding.rs, src/lazy/expanded/mod.rs, src/lazy/mod.rs, src/lazy/reader.rs, src/lazy/sequence.rs, src/lazy/streaming_raw_reader.rs, src/lazy/struct.rs, src/lazy/system_reader.rs, src/lazy/text/encoded_value.rs, src/lazy/text/raw/reader.rs, src/lazy/text/raw/v1_1/reader.rs, src/lazy/text/value.rs, src/lazy/value.rs, src/lazy/value_ref.rs, tests/ion_tests_1_1.rs, tests/lazy_element_ion_tests.rs
This PR:
* Introduces an `IonDataSource` trait with two implementations:
* `IonSlice<impl AsRef<[u8]>`, which reads from byte-array backed fixed streams with no overhead.
* `IonStream<impl io::Read>`, which reads incrementally from a streaming input source with minimal overhead.
* Introduces an `IonInput` trait for types that can be converted to an `IonDataSource`, including `&[u8]`, `Vec<u8>`, `&str`, `File`, etc.
* Introduces a `StreamingRawReader` that wraps an `IonDataSource` and exposes one top-level value at a time as a `LazyValue`.
* Modifies the `Element::read*` and `Element::iter` APIs to use the LazyReader.
* Modifies the `ion-tests` to exercise the `LazyReader`.
* Adds `range()` and `span()` methods for viewing the input bytes that correspond to a given value. There's a lot …
=> Adds a `StreamingRawReader`, switches `Element` to the `LazyReader`

src/element/mod.rs, src/lazy/encoder/mod.rs, src/lazy/encoder/value_writer.rs, src/lazy/encoder/write_as_ion.rs, src/lazy/never.rs
Prior to this PR, the `AnnotatableValueWriter` trait provided many of the same methods as `ValueWriter` for ergonomics. Calls to these methods were delegated to the type returned from `without_annotations()`.
This patch reifies the relationship between `AnnotatableValueWriter` and `ValueWriter` by moving the delegated methods into a blanket implementation of `ValueWriter` for all `AnnotatableValueWriter` implementations. Existing uses of these methods continue to work as expected, but instances of an `AnnotatableValueWriter` implementation can now also be passed into methods that expect an `impl ValueWriter`.
The PR also adds `WriteAsIon` implementations for a variety of Rust int types.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …
=> Adds trait implementations

Cargo.toml, examples/write_log_events.rs, src/element/mod.rs, src/lazy/encoder/mod.rs, src/lazy/encoder/value_writer.rs, src/lazy/encoder/write_as_ion.rs, src/lazy/never.rs
Updates all of the dependencies that were outdated and which could also be upgraded without an invasive code change. Also updates usages of the now-deprecated `chrono::NaiveDateTime::from_timestamp_millis` in the `write_log_events` example.
=> Updates dep versions, remove deprecated method use from example

src/lazy/encoder/binary/mod.rs, src/lazy/encoder/binary/v1_0/container_writers.rs, src/lazy/encoder/binary/v1_0/value_writer.rs, src/lazy/encoder/binary/v1_1/value_writer.rs, src/lazy/encoder/container_fn.rs, src/lazy/encoder/mod.rs, src/lazy/encoder/text/value_writer.rs, src/lazy/encoder/value_writer.rs, src/lazy/encoder/write_as_ion.rs, src/types/symbol.rs
The `ValueWriter` trait's container-writing methods (`write_list`, `write_sexp`, etc) take a closure using [HRTB](https://doc.rust-lang.org/nomicon/hrtb.html), allowing the user to call whatever methods they want on the provided container writer.
Unfortunately, due to a limitation in the compiler's implementation of HRTB evaluation, HRTB lifetimes are over-conservatively [assumed to be `'static`](https://blog.rust-lang.org/2022/10/28/gats-stabilization.html#implied-static-requirement-from-higher-ranked-trait-bounds). This constraint led to a number of workaround warts in the `ValueWriter` trait family.
This PR replaces those closures with a collection of new traits.
*Old signatures*
```rust
fn write_list<F: for<'a> FnOnce(&mut Self::ListWriter<'a>) -> IonResult<()>>(
self,
list_fn: F,
) …
```
=> Simplifies the `ValueWriter` trait family

src/serde/de.rs, src/serde/mod.rs, src/serde/ser.rs
This PR works on adding support for parameterized Rust enums with `experimental-serde` feature.
*Example:*
Below is an example parameterized enum value in Rust:
```rust
#[serde_as]
#[derive(Serialize, Deserialize)]
enum ParameterizedEnum {
Unit,
Newtype(u32),
Tuple(u32, u32),
Struct { a: u32 },
}
```
Ion representation:
```ion
// For each of the enum variant following are corresponding Ion representation
Unit // simply a symbol value 
NewType::1
Tuple::[1, 2]
Struct::{a: 1}
```
- Modified mapping table for serde data types to Ion types.
- Modified serialization to remove adding a new struct for `newtype_variant`, `struct_variant` and `tuple_variant`. Instead add annotation with variant name.
- Modified deserialization to check for annotation …
=> Adds support for parameterized Rust enums in serde

.github/workflows/rust.yml
None
According to https://docs.aws.amazon.com/codebuild/latest/userguide/action-runner.html, we need to start including the run id and run attempt in the "runs on" configuration for CodeBuild-hosted runners.
I've also created a job that functions as a "join" operation for all of the forks from the build matrix. We can use the build confirmation job as the required job for the branch protection rule since it has a stable name.
The codecov workflow is failing for this PR. It looks like it's related to [this issue](https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954), so in theory, it's to be expected for any fork->source PRs (since the workflows for the PR can't access GitHub secrets).
If …
=> Update CodeBuild Runner integration to include the run id and attempt

.github/workflows/rust.yml
None
I noticed that we were running duplicates of the "Setup Matrix" and the "Build and Test Confirmation" jobs in pull requests. This PR fixes that.
=> Update GHA workflow to eliminate some redundant jobs

benches/write_many_structs.rs, examples/write_log_events.rs, src/element/writer.rs, src/lazy/encoder/annotate.rs, src/lazy/encoder/annotation_seq.rs, src/lazy/encoder/binary/v1_0/container_writers.rs, src/lazy/encoder/binary/v1_0/mod.rs, src/lazy/encoder/binary/v1_0/value_writer.rs, src/lazy/encoder/binary/v1_0/writer.rs, src/lazy/encoder/binary/v1_1/container_writers.rs, src/lazy/encoder/binary/v1_1/mod.rs, src/lazy/encoder/binary/v1_1/value_writer.rs, src/lazy/encoder/binary/v1_1/writer.rs, src/lazy/encoder/mod.rs, src/lazy/encoder/text/mod.rs, src/lazy/encoder/text/value_writer.rs, src/lazy/encoder/value_writer.rs, src/lazy/encoder/write_as_ion.rs, src/lazy/encoder/writer.rs, src/lazy/never.rs, src/raw_symbol_token_ref.rs, src/types/mod.rs, src/types/symbol.rs, tests/ion_tests/mod.rs
Adds an `ApplicationWriter` that wraps the various lazy raw writer types and creates new symbol table entries as needed. The new writer is now being used in our `ion-tests` integration.
I intend to rename the `ApplicationWriter` once the legacy writer is removed.
=> Introduces an application-level lazy writer

src/binary/raw_binary_writer.rs, src/element/writer.rs, src/lazy/encoder/text/mod.rs, src/lazy/encoder/text/value_writer.rs, src/lazy/encoder/value_writer.rs, src/serde/de.rs, src/serde/mod.rs, src/serde/ser.rs, src/text/raw_text_writer.rs, src/types/mod.rs
This PR replaces usages of the old `UserWriter` with the new `ApplicationWriter` introduced in #745 (currently under review).
It also modifies the encoding of various serde data types to include type annotations:
<table >
<tr>
<td>Serde type</td>
<td>Example Rust</td>
<td>Old serialization</td>
<td>New serialization</td>
</tr>
<tr>
<td>Unit struct</td>
<td>
```rust
struct Foo;
```
</td>
<td>
<pre>
"Foo"
</pre>
</td>
<td>
<pre>
Foo
</pre>
</td>
</tr>
<tr>
<td>Newtype</td>
<td>
```rust
struct Foo(i32);
```
</td>
<td>
<pre>
1
</pre>
</td>
<td>
<pre>
Foo::1
</pre>
</td>
</tr>
<tr>
<td>Tuple struct</td>
<td>
```rust
struct Foo(i32, i32);
```
</td>
<td>
<pre>
[1, 2]
</pre>
</td>
<td>
<pre>
Foo::[1, 2]
</pre>
</td>
</tr>
<tr>
<td>Struct</td>
<td>
```rust
struct Foo {
x: i32,
y: i32 …
```
=> Modifies the serde serializer to use the new writer

src/serde/de.rs, src/serde/mod.rs, src/serde/ser.rs
Addresses [this comment](https://github.com/amazon-ion/ion-rust/pull/747#issuecomment-2069824799) from PR #747.
Enum variants and struct types are no longer annotated with their Rust type name. Enums _are_ still annotated with their variant name, which can be modified using standard `serde` config attributes.
=> Values are no longer serialized with a type identifier annotation.

src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/binary/raw/v1_1/reader.rs, src/lazy/binary/raw/v1_1/type_descriptor.rs, src/lazy/binary/raw/v1_1/value.rs
*Issue #, if available:* #662
This PR is the first in the chain of scalar value implementations, implementing the parsing of boolean values.
I've tried to keep each value type separated into its own PR, in order to keep the changes trivial and quick to review.. this is proving to be irritating, so I might merge a few.
---
=> Add 1.1 binary reader support for bools

src/lazy/binary/raw/v1_1/value.rs, src/lazy/binary/raw/value.rs, src/lazy/decoder.rs, src/lazy/encoding.rs, src/lazy/expanded/compiler.rs, src/lazy/expanded/e_expression.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/mod.rs, src/lazy/expanded/sequence.rs, src/lazy/expanded/struct.rs, src/lazy/expanded/template.rs, src/lazy/text/buffer.rs, src/lazy/text/encoded_value.rs, src/lazy/text/matched.rs, src/lazy/text/parse_result.rs, src/lazy/text/raw/reader.rs, src/lazy/text/raw/sequence.rs, src/lazy/text/raw/struct.rs, src/lazy/text/raw/v1_1/reader.rs, src/lazy/text/value.rs
Many of the types that comprise the text reader API are quite large. This PR makes a variety of small changes to shrink their layout, hopefully helping to minimize the need for `memcpy`s and reducing bump allocated memory usage. Benchmarks showed modest improvements in the 1-3% range. I suggest reviewing the commits individually.
Following PR #760, field name information is no longer stored in the `LazyRawTextValue`; it has its own type that is only constructed in the context of a struct. Commit 3f68fab3b45a3be577bbc7a577da85cc97cb07b0 modifies text values so that their `TextBufferView` layout starts with the annotations sequence (if any) and ends with the final byte of the value. Prior to this change, many values held a slice that contained the rest of the available input. This change …
=> Text reader implementation cleanup

src/lazy/binary/raw/v1_1/reader.rs, src/lazy/binary/raw/v1_1/type_descriptor.rs, src/lazy/binary/raw/v1_1/value.rs
*Issue #, if available:* #662
Add support for floats to the 1.1 binary raw reader.
---
=> Add 1.1 binary reader support for floats

src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/binary/raw/v1_1/reader.rs, src/lazy/binary/raw/v1_1/sequence.rs, src/lazy/binary/raw/v1_1/type_descriptor.rs, src/lazy/binary/raw/v1_1/value.rs
*Issue #, if available:* #664
This PR adds length-prefixed Lists and S-Expressions to the 1.1 raw binary reader.
---
=> Add 1.1 binary reader support for length-prefixed Lists & S-Expressions

src/binary/decimal.rs, src/lazy/binary/test_utilities.rs, src/lazy/encoder/annotate.rs, src/lazy/encoder/writer.rs, src/lazy/reader.rs, src/serde/ser.rs, src/write_config.rs, tests/ion_tests/mod.rs
Consolidates the `Writer::new()` and `Writer::with_config() methods into a single `new` method that accepts an `impl Into<WriteConfig>`. This allows users to create a writer via code like:
```rust
let mut writer = Writer::new(v1_0::Binary, Vec::new())?;
let mut writer = Writer::new(v1_0::Text.with_format(TextFormat::Pretty), Vec::new())?;
```
=> `Writer::new()` takes an `impl Into<WriteConfig>`

src/lazy/binary/raw/v1_1/reader.rs, src/lazy/binary/raw/v1_1/type_descriptor.rs, src/lazy/binary/raw/v1_1/value.rs
*Issue #, if available:* #662
This PR adds support for typed nulls to the binary ion 1.1 reader.
---
=> Add 1.1 binary reader support for typed nulls

benches/read_many_structs.rs, examples/read_all_values.rs, src/binary/decimal.rs, src/binary/timestamp.rs, src/catalog.rs, src/element/mod.rs, src/lazy/decoder.rs, src/lazy/encoder/text/v1_1/writer.rs, src/lazy/encoder/writer.rs, src/lazy/expanded/compiler.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/mod.rs, src/lazy/reader.rs, src/lazy/sequence.rs, src/lazy/struct.rs, src/lazy/system_reader.rs, src/lazy/system_stream_item.rs, src/lazy/value.rs, src/lazy/value_ref.rs, src/lib.rs, src/read_config.rs, src/serde/de.rs, src/symbol_table.rs, tests/ion_hash_tests.rs
Issue: #776.
> [!TIP]
> A large chunk of this PR's diff comes from mechanical renaming/refactoring that occurred in cf6aacc422970758960eb4b7699d012d6c26ee53. I suggest skimming that one and then reviewing the changes in efd8e22504a401756224f8174c7bd746384e248a more closely.
The recently removed `IonReader` API's `SystemReader` had the ability to import shared symbol tables from a given `Catalog` implementation. This PR adds the same functionality to the lazy reader API's `SystemReader`.
It also normalizes the constructors used for `Reader` and `Writer`. There are no longer exported type aliases for `BinaryReader`, `TextReader`, etc. They are all `Reader<D: Decoder, I: IonInput>`. As part of this change, `Reader::new` now accepts an `Into<ReadConfig<D>>` that allows the user to specify the …
=> Restores shared symbol table import functionality

src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/binary/raw/v1_1/reader.rs, src/lazy/binary/raw/v1_1/struct.rs, src/lazy/binary/raw/v1_1/type_code.rs, src/lazy/binary/raw/v1_1/type_descriptor.rs, src/lazy/binary/raw/v1_1/value.rs, src/lazy/encoder/binary/v1_1/fixed_uint.rs, src/lazy/encoder/binary/v1_1/flex_sym.rs, src/lazy/reader.rs
*Issue #, if available:* #664
This PR adds support to the 1.1 raw binary reader for length-prefixed structs.
---
=> Add 1.1 binary reader support for length-prefixed structs

src/lazy/any_encoding.rs, src/lazy/binary/raw/v1_1/value.rs, src/lazy/binary/raw/value.rs, src/lazy/decoder.rs, src/lazy/encoder/binary/v1_0/value_writer.rs, src/lazy/encoder/binary/v1_1/value_writer.rs, src/lazy/encoder/write_as_ion.rs, src/lazy/encoding.rs, src/lazy/expanded/mod.rs, src/lazy/sequence.rs, src/lazy/streaming_raw_reader.rs, src/lazy/struct.rs, src/lazy/system_reader.rs, src/lazy/system_stream_item.rs, src/lazy/text/value.rs, src/lazy/value.rs, src/types/float.rs, src/types/mod.rs
This PR includes a variety of small fixes and improvements that I found myself needing as I went to upgrade the `ion-cli` to `HEAD`. I'd like to include these in the v1.0-rc4 release. I have completed the `ion-cli` upgrade in my local workspace using this branch, so I'm reasonably confident that these are the last items I need to get in.
* Renames the `RawReaderType` enum to `IonEncoding` because it is generally useful in other contexts too.
* Adds the ability for system and raw readers using `AnyEncoding` to report the encoding they're currently using.
* Adds `value_span` and `annotations_span` methods to `LazyValue`. It already had a `span` method whose bytes included both the annotations and the value.
* The binary 1.0 and 1.1 writers will now write `f64`s as `f32`s to save space when …
=> Additional tooling access methods, trait impls, and a bug fix

src/lazy/any_encoding.rs, src/lazy/binary/raw/v1_1/value.rs, src/lazy/binary/raw/value.rs, src/lazy/decoder.rs, src/lazy/encoder/binary/v1_0/value_writer.rs, src/lazy/encoder/text/v1_0/writer.rs, src/lazy/encoder/text/v1_1/writer.rs, src/lazy/encoder/write_as_ion.rs, src/lazy/text/value.rs
Prior to this change, when a `ValueWriter` explicitly called `with_annotations()` and provided an empty array, the writer would write an empty annotations sequence which is not legal. This change detects that case and skips writing any sequence at all. It also adds a `has_annotations()` convenience method to the `LazyRawValue` trait.
=> Prevent writing empty annotations sequences

src/lazy/any_encoding.rs, src/lazy/binary/raw/reader.rs, src/lazy/binary/raw/v1_1/reader.rs, src/lazy/binary/raw/value.rs, src/lazy/decoder.rs, src/lazy/encoder/text/v1_0/value_writer.rs, src/lazy/streaming_raw_reader.rs, src/lazy/text/buffer.rs, src/lazy/text/raw/reader.rs, src/lazy/text/raw/v1_1/reader.rs
In binary encodings, stream items contain enough data for the reader to tell whether they are complete. In text encodings, it's possible for the buffer to end with data that looks like a complete item but is not. The only way to be certain is to try to read again from the input source to confirm there's no more data. Consider the following examples in which Ion is being pulled from a `File` into a `Vec<u8>`:
```
foo /* comment */   ::bar::baz::1000
└────────┬───────┘ └────────┬───────┘
buffer contents   remaining in File
$ion _1_0
└────────┬───────┘ └────────┬───────┘
buffer contents   remaining in File
75 1.20
────────┬───────┘ └────────┬───────┘
buffer contents   remaining in File
```
To avoid misinterpreting the data, the `StreamingRawReader` now performs a final check for text readers …
=> Enables the StreamingRawReader to detect incomplete text

Cargo.toml, src/lazy/any_encoding.rs, src/lazy/binary/raw/reader.rs, src/lazy/binary/raw/v1_1/reader.rs, src/lazy/raw_stream_item.rs, src/lazy/system_stream_item.rs, src/lazy/text/buffer.rs, src/lazy/text/raw/reader.rs, src/lazy/text/raw/v1_1/reader.rs, src/lazy/value.rs, src/lib.rs, src/symbol_ref.rs, src/types/symbol.rs
Changes:
* Bumps the version to `v1.0.0-rc.6`
* Feature gated:
* Re-exports the `IonEncoding` type
* Allows `RawStreamItem`s to report their `IonEncoding`
* Allows access to a `LazyValue`'s `SymbolTable`
=> Version bump to 1.0.0-rc.6, improvements to IonEncoding

src/lazy/text/matched.rs, src/types/decimal/mod.rs
None
Fixes the logic in `Decimal.precision()` and adds/improves decimal-related test cases.
=> Fixes logic error in Decimal::precision

src/element/mod.rs, src/lazy/text/buffer.rs
None
Fixes a small bug in `match_bool` that was incorrectly reporting things like "fal" as incomplete booleans rather than as non-matches.
Also adds test cases, and updates existing test cases with a more concise macro and the ability to specify whether a value is a mismatch vs an incomplete match.
You may want to view this PR in the "split" diff view.
=> Fix certain symbols being incorrectly identified as incomplete boolean values

src/ion_data/ion_eq.rs, src/ion_hash/type_qualifier.rs, src/lazy/binary/encoded_value.rs, src/lazy/binary/immutable_buffer.rs, src/lazy/binary/raw/v1_1/e_expression.rs, src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/binary/raw/v1_1/value.rs, src/lazy/encoder/binary/v1_1/container_writers.rs, src/lazy/encoder/binary/v1_1/flex_uint.rs, src/lazy/encoder/binary/v1_1/value_writer.rs, src/lazy/encoder/value_writer.rs, src/lazy/encoder/writer.rs, src/lazy/expanded/compiler.rs, src/lazy/expanded/e_expression.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs, src/lazy/expanded/mod.rs, src/lazy/expanded/template.rs, src/lazy/streaming_raw_reader.rs, src/lazy/system_reader.rs, src/lazy/value_ref.rs, src/lib.rs, src/symbol_table.rs, src/text/text_formatter.rs, src/types/decimal/mod.rs, src/types/integer.rs
Adds:
* An implementation of the `(annotate)` TDL form
* Binary read support for `flex_uint::`-encoded template parameters
* Very limited binary write support for `flex_uint::`-encoded template parameters to enable unit testing for the reader.
=> Adds the `(annotate ...)` form and bin read support for `flex_uint` parameters

src/lazy/any_encoding.rs, src/lazy/binary/raw/reader.rs, src/lazy/binary/raw/sequence.rs, src/lazy/binary/raw/struct.rs, src/lazy/binary/raw/v1_1/e_expression.rs, src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/binary/raw/v1_1/reader.rs, src/lazy/binary/raw/v1_1/sequence.rs, src/lazy/binary/raw/v1_1/struct.rs, src/lazy/binary/raw/v1_1/value.rs, src/lazy/binary/raw/value.rs, src/lazy/decoder.rs, src/lazy/expanded/compiler.rs, src/lazy/expanded/e_expression.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs, src/lazy/expanded/mod.rs, src/lazy/expanded/template.rs, src/lazy/raw_stream_item.rs, src/lazy/span.rs, src/lazy/streaming_raw_reader.rs, src/lazy/struct.rs, src/lazy/system_reader.rs, src/lazy/system_stream_item.rs, src/lazy/text/buffer.rs, src/lazy/text/parse_result.rs, src/lazy/text/raw/reader.rs, src/lazy/text/raw/v1_1/reader.rs, src/lazy/value.rs, src/lib.rs
This PR:
* Adds a new trait, `EncodedBinaryValue`, with methods for exposing `Span`s representing the various components of a value's encoding. This trait is implemented by the 1.0 and 1.1 binary value types. These methods allow `ion inspect` to handle both versions' values uniformly.
* Adds `peek` methods to raw container iterators and `MacroExpansion`, allowing tools to see the next value without advancing state.
* Adds an `ExpandedStreamItem` enum that surfaces input `EExp`s in addition to their expansion. This allows tools (like `inspect` to investigate the `EExp` and then investigate its output values.
* Renames `ExpandedValueSource::EExp` to `SingletonEExp`. If a `LazyValue` is backed by an `EExp`, it's because it was found to always expand to a single value at compile time--that …
=> Adds additional tooling APIs to enable Ion 1.1 support in the CLI's `inspect` command

src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/binary/raw/v1_1/type_descriptor.rs
=> Adds binary 1.1 read support for symbol address annotations

src/lazy/expanded/template.rs, src/lazy/text/buffer.rs
Previously the text reader only allowed arguments that could use rest syntax to also be omitted altogether.
=> Allow `?` and `*` parameters to be omitted in tail position

src/lazy/encoder/binary/v1_0/container_writers.rs, src/lazy/encoder/binary/v1_0/value_writer.rs, src/lazy/encoder/binary/v1_1/container_writers.rs, src/lazy/encoder/binary/v1_1/value_writer.rs, src/lazy/encoder/text/v1_0/value_writer.rs, src/lazy/encoder/text/v1_1/value_writer.rs, src/lazy/encoder/value_writer.rs, src/lazy/encoder/value_writer_config.rs, src/lazy/encoder/writer.rs, src/lazy/encoding.rs, src/lazy/expanded/mod.rs, src/lazy/never.rs, src/lazy/struct.rs
Plumbs a `ValueWriterConfig` instance through the application layer value writer types.
=> Adds config option for writing struct field names as text/sid

src/lazy/encoder/text/v1_0/value_writer.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/struct.rs, src/lazy/text/buffer.rs, src/lazy/text/matched.rs, src/lazy/text/parse_result.rs, src/lazy/text/raw/v1_1/reader.rs, tests/ion_tests/detect_incomplete_text.rs, tests/ion_tests/mod.rs
The text reader distinguishes between invalid input and incomplete input. If it encounters incomplete data, it tries to add more data to the buffer and try again. If it encounters invalid data, it surfaces the error to the user.
This PR adds a test utility called `DataStraw`--an `io::Read` implementation that only yields a single byte of input per call to `read()`. By doing this, all subslices of input are tested for correct incompleteness detection.
As you can imagine, this surfaced a number of bugs that needed to be fixed. I've fixed everything the tests surfaced in the Ion 1.1 text parser. In doing so I naturally also fixed the majority of bugs in the Ion 1.0 parser because they share lots of parsing logic. However, I have not set up the same tests for Ion 1.0 yet. I will do that in a …
=> Adds incompleteness detection tests

.github/workflows/miri.yml, src/lazy/encoder/binary/v1_0/writer.rs, src/lazy/encoder/binary/v1_1/writer.rs, src/lazy/expanded/mod.rs, src/unsafe_helpers.rs
Related to #794.
Miri's [tree borrows](https://perso.crans.org/vanille/treebor/index.html) aliasing model is more permissive than stacked borrows (the default), which is known to reject some programs that are actually safe.
This PR configures our CI `miri` check to use tree borrows and addresses several of Miri's complaints. This is enough to satisfy the tests currently in CI (the tests for the experimental `serde` feature).
There are still some issues to investigate. When running Miri on the entire test suite, it complains about at least one more problem, though it's unclear whether it's actually a potential problem or another limitation in its aliasing model. This patch is an improvement, however, and I'd rather not block these changes as we look into the others.
By submitting this pull …
=> Configures Miri to use tree borrows, fixes remaining errors

src/lazy/expanded/compiler.rs, src/lazy/expanded/macro_table.rs, src/lazy/expanded/template.rs, src/lazy/system_reader.rs
This builds on PR #821. It also borrows from and supersedes the changes in @jobarr-amzn's PR #818.
Modifies the `TemplateCompiler` to resolve macro IDs in the table of 'pending' macros (defined in the current encoding directive) rather than the active macro table. This allows macros to depend on previously defined macros.
> [!NOTE] 
> `cargo fmt` did some reflows that accounts for ~half of the diff. Fortunately, all of the formatting changes occur in a contiguous block at the end of the PR. I've added a PR tour comment showing where that begins.
=> Enables dependent macros

src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/binary/raw/v1_1/type_code.rs, src/lazy/binary/raw/v1_1/type_descriptor.rs, src/lazy/encoder/binary/v1_1/value_writer.rs
Prior to this PR, e-expressions with an address between `0..64` could be encoded as a single-byte opcode and larger e-expressions could only be encoded as a length-prefixed e-expression.
This patch adds read and write support for binary e-expressions that have a trailing 1- or 2-byte `FixedUInt` to complete the address.
=> Adds support for eexps with 12- and 20-bit addresses

src/lazy/expanded/e_expression.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs, src/lazy/expanded/sequence.rs, src/lazy/expanded/template.rs, src/lazy/sequence.rs, src/lazy/text/buffer.rs
This PR implements the `make_sexp` macro, allowing a macro body to include dynamically populated (i.e. not `(literal ...)`) s-expressions.
Combined with `annotate`, this enables macros to produce system values like encoding directives. For example:
```ion
$ion_encoding::(
(macro def_macros ($macros*)
(annotate
(literal $ion_encoding)
(make_sexp [
(make_sexp [
(literal macro_table),
$macros
])
])
)
)
)
(:def_macros
(macro foo () 1)
(macro bar () 2)
(macro baz () 3))
(:foo)
(:bar)
(:baz)
```
produces
```ion
1 2 3
```
=> Adds `make_sexp` macro, enabling output of system values

Cargo.toml, src/lazy/binary/raw/v1_1/value.rs, tests/conformance.rs, tests/conformance_dsl/clause.rs, tests/conformance_dsl/context.rs, tests/conformance_dsl/continuation.rs, tests/conformance_dsl/document.rs, tests/conformance_dsl/fragment.rs, tests/conformance_dsl/mod.rs, tests/conformance_dsl/model.rs, tests/conformance_tests.rs, tests/detect_incomplete_text.rs, tests/element_display.rs, tests/ion_data_consistency.rs, tests/ion_tests/lazy_element_ion_tests.rs, tests/ion_tests/mod.rs
This PR adds an implementation of the conformance DSL, along with a runner for testing conformance tests during CI/CD, and a separate runner that can be used to target files more ad-hoc. The ion-tests submodule has also been updated in order to pull in the conformance tests, which also required some updates to the `test_resource` paths for 1.0.
Most of the code is modeled directly after the grammar. Documents contain fragments and a continuation. Expectations, which are a subset of continuations, act as terminal nodes and trigger the evaluation of the test. Context tracks the fragments, version, and encoding, for the test's evaluation path.
```
$ cargo test -F experimental --test conformance_tests
Compiling ion-rs v1.0.0-rc.7 …
```
=> Add conformance testing DSL

src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/binary/raw/v1_1/type_code.rs, src/lazy/binary/raw/v1_1/type_descriptor.rs, src/lazy/binary/raw/v1_1/value.rs, src/lazy/encoder/binary/v1_1/flex_sym.rs
This PR aims to merge some optimizations that were implemented in a demo branch a while back. In particular, it:
* moves the logic needed to determine the `LengthType` for a given `Opcode` from runtime to compile time, streamlining the process of reading a value/e-expression.
* adds an `OpcodeKind` to the `Opcode` struct, allowing the reader to check for high-level categories of syntactic elements like "value", "e-expression", or "annotations" rather than matching against all possible `OpcodeType`s in each category.
* Batches up parsed e-expression arguments and copies them to the bump allocator in bulk.
=> Adds `OpcodeKind`, `LengthType` to Opcode

src/element/sequence.rs, src/types/list.rs, src/types/sexp.rs
None.
I was working on something else, and having a hard time coming up with a clean way to deal with an input that could be a `Vec<Element>` or `Sequence`. It makes it so much easier to write APIs that can accept a borrowed, ordered collections of `Element` if we can use `AsRef<[Element]>`.
=> Adds AsRef<[Element]> for Sequence, List, and SExp

.github/workflows/rust.yml, Cargo.toml, src/lazy/any_encoding.rs, src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/binary/raw/v1_1/struct.rs, src/lazy/decoder.rs, src/lazy/encoder/binary/v1_1/value_writer.rs, src/lazy/encoder/text/v1_1/writer.rs, src/lazy/encoder/writer.rs, src/lazy/expanded/compiler.rs, src/lazy/reader.rs, src/lazy/system_reader.rs, src/lib.rs, tests/conformance.rs, tests/conformance_dsl/mod.rs, tests/conformance_tests.rs, tests/detect_incomplete_text.rs, tests/ion_tests_1_1.rs
I tried to make this as minimally invasive as possible:
* The `experimental-ion-1-1` feature enables`experimental-reader-writer`
* The `experimental` feature flag enables `experimental-ion-1-1`
* When `experimental-ion-1-1` is not enabled
* the `v1_1` module is only `pub(crate)`
* the decoder doesn't have a match arm for the `(1, 1)` version.
* the tests for switching versions have a branch that checks that an `Err` is returned for an Ion 1.1 IVM
* the conformance dsl tests and a number of Ion 1.1 specific tests are disabled (omitted from compilation, really)
* When `experimental-ion-1-1` is enabled, all APIs and behaviors are as they were prior to this PR
I also updated the build workflow to _not_ cancel all outstanding jobs if one …
=> Put Ion 1.1 support behind a feature flag

src/lazy/binary/raw/v1_1/value.rs, tests/conformance_dsl/context.rs, tests/conformance_dsl/continuation.rs, tests/conformance_dsl/document.rs, tests/conformance_dsl/fragment.rs, tests/conformance_dsl/mod.rs, tests/conformance_dsl/model.rs, tests/conformance_tests.rs
This PR adds missing symbol notation for Toplevel and Produces clauses.
This turned out to be a lot simpler than I had originally thought. My first (few) pass(es) through the spec left my understanding to be that the notation could define symbol mappings, which would have to be created during the evaluation of the fragments, and supported when evaluating expectations. Unfortunately I didn't realize my misunderstanding until after having implemented creating the symbol mappings.
The functionality now allows symbol IDs to be specified as quoted symbols, with the `#$` notation for identifying such symbol IDs.
When the Toplevel fragment is triggered to encode it's contents into a new document fragment, it uses `ProxyElement` to wrap each …
=> Update conformance testing DSL to support unknown symbols

src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/binary/raw/v1_1/struct.rs, src/lazy/expanded/compiler.rs, src/lazy/expanded/e_expression.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs, src/lazy/expanded/mod.rs, src/lazy/expanded/template.rs, src/lazy/reader.rs, src/lazy/system_reader.rs, src/lazy/text/buffer.rs, tests/conformance_dsl/clause.rs, tests/conformance_dsl/fragment.rs, tests/conformance_tests.rs, tests/ion_tests_1_1.rs
* Macro invocation syntax is now `(.macro_name)`
* Variable expansion syntax is now `(%variable_name)`
* The `void` macro has been renamed to `none`
* Pulls in the latest version of `ion-tests`, which includes amazon-ion/ion-tests#125
I suggest looking at the commits individually.
=> TDL syntax updates

src/lazy/streaming_raw_reader.rs, tests/detect_incomplete_text.rs
https://github.com/amazon-ion/ion-cli/issues/162
Updates the `StreamingRawReader` to treat end-of-stream as a potential (not yet started) incomplete value.
I have verified that this does actually fix the problem mentioned in amazon-ion/ion-cli#162.
This might be improved by separating the end-of-stream condition from the incomplete value condition so that we can find a way to discard the "non-value" data. That way we don't need to keep holding e.g. a 2000 word comment in memory just to read the next top-level value.
=> Treat end-of-stream as a potential unstarted, incomplete value in StreamingRawReader

Cargo.toml, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs
* Updates the `append_macros` macro name to `add_macros`.
* Enables optimizations for dependencies (but not `ion-rust` itself) in debug builds, speeding up test runs without affecting incremental build times.
=> Renames `append_macros` to `add_macros`

src/lazy/any_encoding.rs, src/lazy/binary/raw/v1_1/e_expression.rs, src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/span.rs
For use in tooling, particularly `ion inspect`. These methods allow an application to access the encoded subfields of a binary 1.1 e-expression.
Related to amazon-ion/ion-cli#181.
=> Adds binary eexp subfield span accessors

.github/workflows/coverage.yml
=> Updates codecov.io GH action

src/lazy/decoder.rs, src/lazy/expanded/e_expression.rs, src/lazy/expanded/sequence.rs, src/lazy/sequence.rs
This PR contains no new features, just a refactor.
There are some complex generics around the `RawValueExpr` type (described in dev comments therein) that made writing a centralized, reusable `resolve` method difficult to express. I guess I'm older and wiser now, though, 'cause I managed to figure it out this time around.
Along with adding the `resolve` method, I removed two places where the same logic had been implemented.
=> Adds reusable `RawValueExpr::resolve` method

src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs
*Issue #, if available:* Contributes to #661
*Description of changes:* Defines `set_macros`, `set_symbols`, and `add_symbols`, as described in [the Ion 1.1 spec](https://amazon-ion.github.io/ion-docs/books/ion-1-1/macros/system_macros.html). 
=> Flesh out set/add macros/symbols

src/element/mod.rs, src/element/sequence.rs, src/lib.rs, src/result/conversion.rs, src/result/mod.rs
This PR includes a couple changes intended to make working with owned `Element`s easier are not require cloning for 'projecting' an element to be replaced by something it contains.
- Exposes `OwnedSequenceIterator` and modifies its implementation to clone less
- Adds `try_into_<x>` methods similar to `as_<x>` methods on `Element`
-  These allow 'partial' conversions of owned `Element`s with the 'failure' case returning the original `Element`
Example simplified usage:
```rust
#[derive(Debug)]
enum ElementIterator {
Single(Element),
Sequence(OwnedSequenceIterator),
}
...
match elt.try_into_sequence() {
Err(elt) => ElementIterator::Single(elt),
Ok(seq) => ElementIterator::Sequence(seq.into_iter()),
}
```
---
By submitting this pull request, I confirm that my contribution is made under the …
=> API improvements for usage of owned `Element`s

src/lazy/encoder/value_writer.rs, src/lazy/expanded/e_expression.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs, src/lazy/expanded/template.rs
=> Implements `make_symbol` system macro

src/lazy/binary/raw/v1_1/e_expression.rs, src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/binary/raw/v1_1/value.rs, src/lazy/expanded/macro_evaluator.rs
=> Adds binary read support for delimited arg groups

src/lazy/binary/raw/v1_1/e_expression.rs, src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/binary/raw/v1_1/value.rs, src/lazy/encoder/binary/v1_1/writer.rs, src/lazy/expanded/macro_evaluator.rs
Fixes #865.
The raw writer has an encoding buffer stored in its bump allocator.
As values are written, their serialized bytes are written to the encoding buffer.
When `flush()` is called, the encoding buffer's bytes are copied to output and the bump allocator is reset.
However, the writer was _not_ clearing the `encoding_buffer_ptr`, which continued to refer to a (now invalid) memory region in the bump.
That memory still contained the old encoding buffer and so would result in the old data being written out again.
The 1.0 writer had the correct behavior and a cleaner implementation in general, so I copied it over.
=> Raw 1.1 writer now clears encoding buffer on `flush()`

benches/read_many_structs.rs, src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/encoder/text/v1_1/writer.rs, src/lazy/encoder/writer.rs, src/lazy/expanded/compiler.rs, src/lazy/expanded/encoding_module.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs, src/lazy/expanded/mod.rs, src/lazy/reader.rs, src/lazy/system_reader.rs, src/lazy/text/buffer.rs, src/lazy/text/raw/v1_1/reader.rs
This patch modifies `EncodingContext` to have an empty macro table when constructed for use in Ion 1.0 readers.
This allows the Ion 1.0 reader to be used in the process of bootstrapping the Ion 1.1 system macro table, which was previously not possible due to the (now eliminated) circular dependency between macros and readers.
System macros that can be expressed in TDL are now constructed from a template definition encoded in Ion 1.0. As a result, the system macro table initialization logic is now substantially easier to read and more straightforward to modify.
=> Overhauls system macro table bootstrapping

src/constants.rs, src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/binary/raw/v1_1/reader.rs, src/lazy/binary/raw/v1_1/struct.rs, src/lazy/encoder/writer.rs, src/lazy/expanded/compiler.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs, src/lazy/system_reader.rs, src/lazy/system_stream_item.rs, src/lib.rs, tests/conformance_dsl/fragment.rs, tests/conformance_tests.rs
Builds on PR #872.
Switches encoding directive syntax from:
```ion
$ion_encoding::(/*...*/)
```
to:
```ion
$ion::(module _ /*...*/)
```
in anticipation of multi-module support.
=> Switches from "encoding module" to "default module"

benches/read_many_structs.rs, src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/encoder/text/v1_1/writer.rs, src/lazy/expanded/e_expression.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs, src/lazy/expanded/mod.rs, src/lazy/expanded/sequence.rs, src/lazy/expanded/template.rs, src/lazy/sequence.rs, src/lazy/system_reader.rs, src/lazy/text/buffer.rs, src/lazy/text/raw/v1_1/reader.rs
Changes:
* Modifies the system macro table to allow macros to easily depend on earlier macros
* Adds an implementation of the `flatten` macro
* Defines `make_list` as a template that leverages `flatten`
* Re-defines `make_sexp` as a template that leverages `flatten`
* Removes old bespoke impl of `make_sexp`
* Defines `meta` as a template that leverages `none`
=> Implements `flatten`, `make_list`, `meta`

src/lazy/expanded/compiler.rs, src/lazy/expanded/e_expression.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs, src/lazy/expanded/template.rs
Implements:
* `if_none`
* `if_some`
* `if_single`
* `if_multi`
* `default` (in terms of `if_none`)
=> Implements `if_none` and friends

src/lazy/expanded/e_expression.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs, src/lazy/expanded/mod.rs, src/lazy/expanded/struct.rs, src/lazy/expanded/template.rs, src/lazy/struct.rs
A follow-on PR will implement `make_field`.
=> Implements `make_struct`

src/lazy/expanded/e_expression.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs, src/lazy/expanded/struct.rs, src/lazy/expanded/template.rs, src/lazy/struct.rs
=> Implements the `make_field` system macro

src/constants.rs, src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/binary/raw/v1_1/reader.rs, src/lazy/encoder/binary/v1_1/value_writer.rs, src/lazy/encoder/writer.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs, src/lazy/expanded/struct.rs, src/lazy/text/raw/v1_1/reader.rs
=> Restacks the 1.1 system symbol and macro tables

src/element/mod.rs, src/element/sequence.rs, src/lazy/encoder/annotation_seq.rs, src/lazy/encoder/binary/v1_0/container_writers.rs, src/lib.rs, src/result/conversion.rs, tests/conformance_dsl/clause.rs, tests/conformance_dsl/continuation.rs, tests/conformance_dsl/document.rs, tests/conformance_dsl/fragment.rs, tests/conformance_dsl/model.rs, tests/conformance_tests.rs
=> Updates `ion-tests`, conformance test runner bugfixes

Cargo.toml, src/lazy/any_encoding.rs, src/lazy/binary/raw/v1_1/e_expression.rs, src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lib.rs
* Version bump to `1.0.0-rc.10`
* Exposes types needed for the `ion-cli` to traverse eexp argument groups
* Enables reading e-expressions in delimited struct field value position
=> Expose `EExpArgGroup` and related types, version bump

src/lazy/binary/raw/v1_1/immutable_buffer.rs, src/lazy/expanded/compiler.rs
This PR:
* Allows macro definitions to refer to previously defined macros by their address within the current scope.
* Adds a completeness test that was missing for length-prefixed e-expressions.
* Fixes many calls to `IonResult::incomplete` which provided redundant label text.
=> Support for unqualified macro addresses in TDL

src/element/mod.rs, src/lazy/any_encoding.rs, src/lazy/encoder/binary/v1_1/value_writer.rs, src/lazy/encoder/value_writer.rs, src/lazy/encoder/value_writer_config.rs, src/lazy/encoder/writer.rs, src/lazy/encoding.rs, src/lib.rs, src/symbol_table.rs, tests/conformance_dsl/fragment.rs, tests/conformance_dsl/model.rs
=> Makes `AnnotatableWriter` and writer's symbol table experimentally pub

src/lazy/any_encoding.rs, src/lazy/binary/raw/v1_1/value.rs, src/lazy/binary/raw/value.rs, src/lazy/decoder.rs, src/lazy/encoder/binary/v1_1/flex_sym.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/mod.rs, src/lazy/expanded/sequence.rs, src/lazy/expanded/struct.rs, src/lazy/expanded/template.rs, src/lazy/text/value.rs, src/lib.rs
This PR adds lots of new tooling methods and bookkeeping:
* Tags each value with the variable that produced it, if any.
* Renames `UnexpandedField` to `FieldExpr`, which is much clearer.
* Adds container iterators that yield both macro invocations _and_ their expansions, allowing tooling to see both and work with whatever they need.
* Adds `Span` accessor for the delimited `END` byte.
=> Container tooling

src/element/mod.rs, src/types/bytes.rs
Allows deconstruction owned `Element`s and `Bytes` into their contained data.
See also previous enhancements to ergonomics of owned `Element`s
Cf. https://github.com/amazon-ion/ion-rust/pull/858
Cf. https://github.com/amazon-ion/ion-rust/pull/866
---
=> Add deconstructing conversions for owned Elements

src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/mod.rs, src/lazy/expanded/struct.rs, src/lazy/text/buffer.rs, src/lazy/text/mod.rs, src/lazy/text/token_kind.rs
Builds on #892, the PR to port to `winnow`.
I thought there might be a performance boost to be had by computing the mapping from a text value's first byte to the value's kind at compile time and using a lookup table at runtime. Strangely, it didn't change the performance at all--benchmark results are identical.
I'm inclined to merge this anyway just so people don't spend time following the same line of reasoning in the future. Subjectively, it's a bit tidier.
=> Statically computes text value kind lookup table

Cargo.toml, benches/encoding_primitives.rs, src/lazy/encoding.rs, src/lazy/text/buffer.rs, src/lazy/text/matched.rs, src/lazy/text/parse_result.rs, src/lazy/text/raw/reader.rs, src/lazy/text/raw/sequence.rs, src/lazy/text/raw/struct.rs, src/lazy/text/raw/v1_1/reader.rs
This PR restores error reporting details that were lost in #892 and adds more using winnow's `context`.
Example:
It also makes top-level trailing whitespace optional so containers at the end of a stream don't need to be parsed twice at EOF.
=> Improved error reporting

src/text/text_formatter.rs
=> Don't escape `/` in pretty-printed strings

Cargo.toml, src/lazy/text/buffer.rs
*Issue https://github.com/amazon-ion/ion-rust/issues/904*
This PR adds location information to the underlying text buffer. The location information includes row and column value for the buffer input data.
*Row Calculation*
Row numbers start at 1 and increment with each newline character encountered in the input. This maintains consistency with common text editor line numbering.
Row calculations will be based on occurrence of newline characters `\r` and `\n`. These characters have different implications in different OS systems. In order to correctly count the row position:
1. Consider `\r\n` as a single count if they appear together in the input.
2. Count the total occurrences of `\r` and `\n` characters individually.
3. Subtract count in step 1 from count in step …
=> Adds location information to text buffer

Cargo.toml, src/lazy/text/buffer.rs
This PR works on adding an `experimental-location` feature flag for the location-metadata implementation. This allows users to opt-in based on their performance requirements.
- define `experimnetal-location` feature flag in the `Cargo.toml`.
- add configuration wherever row and column properties are used or updated in the `TextBuffer`.
=> Adds experimental-location feature flag

tests/conformance.rs, tests/conformance_tests.rs
*Issue #, if available:* #902
This PR adds a skip list to the conformance tests run during CI/CD, while also adding all of the current conformance tests to the generated unit tests.
The skip list is implemented to skip test files, which may contain multiple tests. This was done because tests are not required to have a name, and many of them do not. This means that a test file cannot be removed from the skip list until each test within passes. I'll be tracking all of the individual tests, and can post a more detailed list, which I will also be sharing with the team shortly. The comments captured in the skip list are mostly the first error to trigger the test failure. I'll keep them updated as I work through them, but the list I'll share will be the most accurate …
=> Update ion-tests and start cataloging conformance issues.

src/lazy/encoder/text/v1_1/value_writer.rs, tests/conformance_dsl/mod.rs
*Issue #, if available:* #914
This PR adds a space between the macro id and the (potential) first argument when creating a new eexp writer.
The eexp writer treats eexp as a standard container with opening, closing, and intra delimiters. The starting `(:` and macro id are treated as the opening delimiter. When serializing to a single line the first argument does not get any delimitation before being written resulting in the macro id and first argument merging together.
An example of this occurring in the conformance tests can be seen with the unit test added in this PR:
The error:
```
ConformanceError(ConformanceErrorImpl {
file: "",
test_name: "",
kind: IonError(Decoding(DecodingError {
description: "could not find macro with id LocalName(\"twicefoo\")\n    while …
```
=> Add trailing space when writing eexp macro symbol

src/types/symbol.rs
None
Makes `static_text(text: &'static str) -> Symbol` a `const` function.
=> Makes Symbol::static_text a const fn

src/element/annotations.rs, src/element/mod.rs, src/element/sequence.rs, src/ion_data/ion_data_hash.rs, src/ion_data/ion_ord.rs, src/ion_data/mod.rs, src/types/bytes.rs, src/types/decimal/coefficient.rs, src/types/decimal/mod.rs, src/types/integer.rs, src/types/list.rs, src/types/mod.rs, src/types/sexp.rs, src/types/string.rs, src/types/struct.rs, src/types/symbol.rs, src/types/timestamp.rs, tests/ion_data_consistency.rs
None, but this is needed for Ion Schema Rust.
* Adds `IonDataHash` trait with implementations for `Element`, `Value`, etc.
* Implements `Hash` for `IonData` using `IonDataHash`.
* Adds regular `Hash` for some other types where it makes sense, such as the `IonType` and `TimestampPrecision` enums.
* Adds integer values to `coefficient::Sign` so that it can be cast to an integer value. (I could have just added `derive(Hash)`, but this seemed like a useful little improvement.)
=> Adds IonDataHash to enable Hash for IonData

tests/conformance_tests.rs
*Issue #, if available:* #902
This PR extends the conformance unit test runner to allow skipping of tests within a test file, rather than forcing all tests in the file to be skipped.
While reviewing currently failing tests it became apparent that there were plenty of successful tests that were not able to be run through CI/CD because of a single, or small number, of other failing tests within the file.  With this PR we can start to include a lot of those successful tests, and have a more accurate in-code documentation of what is failing. This will become more relevant as the number of failing tests is reduced.
This is just a first pass at the functionality. I'll probably extend the `skip` macro so it doesn't have to be repeated, but I wanted to get this …
=> Extend the conformance test skip list to allow skipping tests not just files.

tests/conformance_dsl/continuation.rs, tests/conformance_dsl/mod.rs, tests/conformance_tests.rs
*Issue #, if available:* #916
Prior to this PR the conformance DSL would only parse the first `Then` or `Each` clause in a document or document-like. This lead to false positives where only the first branch in a document would be evaluated.
This PR adjusts the parsing of documents to correctly pack multiple extension into `Continuation::Extensions` which handles evaluating the extensions in sequence.
Additionally, this PR adds 3 more skip list entries, and reduces the tests skipped in `invoke_ee.ion` and `invoke_cardinality_ee.ion`. The additional skip entries are due to this PR fixing `Then` sequences, which added previously ignored test branches to the tests.
---
By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> Fix parsing of conformance test documents with multiple extension clauses (like `Then`)

tests/conformance_dsl/fragment.rs, tests/conformance_dsl/mod.rs
*Issue #, if available:* #931
This PR is simple, and just wraps any argument of an e-exp invocation in `ProxyElement` when transcribing, in order to allow arguments to support being transcribed invocations.
Prior to this PR, providing a conformance DSL eexp invocation such as `(toplevel ('#$foo' ('#$bar)))` would end up being serialized as `(:foo ('#$bar'))`.
---
=> Transcribe eexp invocations for arguments of transcribed invocations.

examples/read_all_values.rs, src/element/mod.rs, src/lazy/expanded/mod.rs, src/lazy/expanded/template.rs, src/lazy/reader.rs, src/lazy/streaming_raw_reader.rs, src/lazy/value.rs, tests/conformance_dsl/context.rs, tests/conformance_dsl/fragment.rs, tests/conformance_dsl/mod.rs, tests/conformance_tests.rs
None.
The main substance of this commit is the first commit, in [src/element/mod.rs](https://github.com/amazon-ion/ion-rust/compare/main...popematt:ion-rust:main?expand=1#diff-91c614c02808b6b0727c79965075d97b2882d5c7c06267d31273a99596bb6f17). I literally just added a trivial implementation of `AsRef<Element>`. I was surprised there isn't already a blanket implementation like `impl AsRef<T> for T`, but it looks like it's due to [a restriction in Rust's type system](https://doc.rust-lang.org/std/convert/trait.AsRef.html#reflexivity).
Why is this change needed? This will allow us, in `ion-schema-rust`, to define things that can be generic over `Element` and `&Element` because we can just accept `AsRef<Element>`.
In the second commit, …
=> Implement AsRef<Element> for Element

Cargo.toml, src/lazy/expanded/mod.rs, src/lazy/streaming_raw_reader.rs, src/lazy/text/buffer.rs, src/lazy/value.rs
This PR removes the previous implementation for location calculation in text buffer. It also removes feature flag `lazy-source-location` since the current implementation for location shows performance as close to main branch.
- Removed all implementation of location calculation in text buffer.
- Removed `lazy-source-location` feature flag from current implementation. The performance for lazy /current approach is close to the main branch(~2% regression to main branch, only for scanning data, for reads same performance)
*Benchmarks:*
Lazy Bookkeeping on Flushes (compared to old text buffer solution (#922))
* Significant performance improvements over previous implementation of location support
*  Scan operations: ~17% …
=> Removes location calculation from buffer and feature flag

src/lazy/expanded/mod.rs, tests/conformance_dsl/context.rs, tests/conformance_dsl/document.rs, tests/conformance_dsl/fragment.rs, tests/conformance_tests.rs
*Issue #, if available:* #937, #936.
This PR addresses 2 issues found during work on conformance testing. The first, is that when reading with AnyEncoding the encoding context would not be reset unless a new ion version was used. The second issue, was that the conformance DSL was rendering each fragment using a new writer, which lead to each fragment having its own IVM.
The redundant IVMs caused issues with the conformance DSL's reader which uses the required version and encoding. When testing some failures (due to context reset) in the CLI we found that the AnyEncoding was not resetting the encoding context as expected.
This PR addresses each by:
* Removing a check that would only reset the context at the start of a stream, or when a new IVM with a different ion …
=> Reset encoding context whenever IVM encountered & update conformance DSL fragment rendering.

src/lazy/expanded/mod.rs, src/lazy/streaming_raw_reader.rs, src/lazy/value.rs, src/location.rs
None.
I discovered that the source location was being reported correctly for top-level values, but that any nested value simply reported the location of its top-level ancestor. This fixes that issue, and in the process, it also fixes #944.
I benchmarked this change, and it is performance-neutral compared to the current tip of `main`.
In the process of working on this, I also realized that row/column location is incorrectly available for Ion binary. I have added a test case to reproduce the problem in `value.rs`, but annotated it as `#[ignore]` because I don't yet know what is the right solution. See #951.
=> Fixes location metadata to support nested values

src/lazy/any_encoding.rs, src/lazy/binary/raw/v1_1/value.rs, src/lazy/binary/raw/value.rs, src/lazy/decoder.rs, src/lazy/text/value.rs, src/lazy/value.rs
fixes #951 
Adds an `encoding()` method to lazy raw values so that a lazy value can call `self.raw().encoding()` and determine what `IonEncoding` (if any) is backing the current lazy value, and then avoid returning a row/column location for values that are backed by binary Ion.
I also significantly refactored the value location tests, and in doing so, I discovered a few more bugs. The affected test cases are commented out, and I opened #954 and #955.
=> Stop providing misleading row/column locations for binary Ion

src/lazy/any_encoding.rs, src/lazy/binary/binary_buffer.rs, src/lazy/binary/raw/reader.rs, src/lazy/binary/raw/sequence.rs, src/lazy/binary/raw/struct.rs, src/lazy/binary/raw/value.rs, src/lazy/encoder/binary/v1_1/flex_int.rs, src/lazy/encoder/binary/v1_1/flex_uint.rs, src/lazy/encoding.rs
The `LazyRawBinaryValue_1_0` type contains a lot of data. While it is `Copy`, it is large enough that making copies of it or moving it around the stack causes a noticeable slowdown. Several other types contain a `LazyRawBinaryValue_1_0` transitively, meaning that this impacts many code paths.
This PR changes the `Binary_1_0` implementation of `Decoder` to use a `Value` type of `&'top LazyRawBinaryValue_1_0<'top>` (a bump-allocated reference) instead of `LazyRawBinaryValue<'top>` (a complete value). This allows copies and moves to happen using a pointer (8 bytes) instead of ~100 bytes of struct data.
This approach is already used by the 1.1 equivalent type, `LazyRawBinaryValue_1_1`, with similar benefits.
I'll make follow-on PRs to do this for the text types too.
Improvement over `HEAD`: …
=> Bump-allocates Binary 1.0 values

src/binary/decimal.rs, src/lazy/encoder/binary/v1_1/value_writer.rs, src/types/decimal/coefficient.rs, src/types/decimal/mod.rs, src/types/timestamp.rs
Cuts `Decimal` from 48 bytes (23 bytes padding) to 32 bytes (7 bytes padding). See the layout comment in the PR for details.
Many types contain a `Decimal`, including `Timestamp` and `ValueRef`, so this removes 16 bytes from many types. Binary 1.0 benchmarks showed that scanning is ~5% faster.
=> Optimize the layout of `Decimal`

tests/conformance_dsl/fragment.rs, tests/conformance_dsl/mod.rs, tests/conformance_tests.rs
*Issue #, if available:* #935
Prior to this PR using an expression group within a `toplevel` clause would fail. The existing code captured the `::` for a normal expression group, but due to the DSL's transcription syntax we need to capture `#$::` and construct an expression group through the eexp writer.
This PR captures the `#$::` notation, and constructs the expression group via the writer.
Two tests were also added to the conformance DSL unit tests to ensure the behavior as well.
---
=> Add expression group transcription to conformance DSL

tests/conformance_dsl/clause.rs, tests/conformance_dsl/fragment.rs, tests/conformance_dsl/mod.rs, tests/conformance_tests.rs
*Issue #, if available:* #971
This PR implements the `symtab` clause, which is the symbol table partner to `mactab`, providing a shorthand clause for defining a new symbol table.
This implementation uses the ion 1.0 symbol table syntax.
An example would be a document like,
```
(ion_1_1 (symtab "a" "b") (text "$2") (produces b))
```
where the `(symtab "a" "b")` expands to `(toplevel $ion_symbol_table::{symbols: ["a", "b"]})`.
It might be worth checking the ion version of the context at render time, and expand this to a 1.1 module-based symbols definition.
---
=> Implement symtab clause for conformance DSL

src/lazy/expanded/e_expression.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs, src/lazy/expanded/template.rs, tests/conformance_dsl/continuation.rs, tests/conformance_tests.rs
*Issue #, if available:* #942
This PR adds an implementation for the builtin system macro `repeat`.
In addition to the builtin implementation, I've also updated the conformance test skip-list to skip the only test in `system_macros/default.ion` that fails, and to remove `system_macros/repeat.ion` which now passes.
```
Running tests: ion-tests/conformance/system_macros/repeat.ion
repeat can be invoked                                             ...  [Ok]
repeat can produce                                                ...  [Ok]
repeat will ignore any annotations on the number of repetitions   ...  [Ok]
repeat signals an error when                                      ...  [Ok]
```
---
By submitting this pull request, I confirm that my contribution is made under …
=> Implement `repeat` system macro.

src/lazy/expanded/e_expression.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs, src/lazy/expanded/template.rs, tests/conformance_tests.rs
*Issue #, if available:* #942
This PR adds an implementation for the `sum` system macro.
In addition this PR removes `conformance/system_macros/sum.ion` from the skip-list.
```
Running tests: ion-tests/conformance/system_macros/sum.ion
sum can be invoked                                              ...  [Ok]
sum produces a single, unannotated integer that is the sum of   ...  [Ok]
sum is commutative                                              ...  [Ok]
sum arguments may not be                                        ...  [Ok]
```
---
=> Implement sum system macro

tests/conformance_tests.rs
*Issue #, if available:* #972
Prior to this PR the conformance test `data_model/decimal.ion` was in the skip-list due to the parsing error identified in #972. With that issue addressed, we can now remove most of that set of tests from the skip-list.
This PR does just that. There is only 1 failing test in `data_model/decimal.ion` now, due to a VarInt size that ion-rust does not currently support.
---
=> Remove all but one test from skiplist for data_model/decimal.ion

Cargo.toml, src/serde/de.rs, src/serde/mod.rs, src/serde/ser.rs
*Issue #, if available:* #978
This PR adds support for nested variant types, allowing something like:
```rust
#[derive(Serialize, Deserialize, PartialEq, Debug)]
enum Outter {
First(Inner),
}
#[derive(Serialize, Deserialize, PartialEq, Debug)]
enum Inner {
Second(u32),
}
// 
let value = Outter::First(Inner::Second(3));
let value_str = to_string(&value).unwrap();
println!("{}", value_str); // prints: "First::Second::3"
```
On the serialization side this PR adds a new vector of `&'static str` to hold the list of variant names that will be used for annotations.  Once a serializable type is reached the annotations are given to the writer and the type is serialized.
On the deserialization side, we need to keep track of how deep the nesting goes so that we can pull the …
=> Add support for nested variant types

Cargo.toml, src/types/decimal/mod.rs
*Issue #, if available:* #985
*Description of changes:* Implements `TryFrom<BigDecimal> for Decimal` and `TryInto<BigDecimal> for Decimal`. 
If the `bigdecimal` feature is enabled these conversions will be available for accessing components of the Decimal or for doing math. 
=> Implement conversions to/from BigDecimal for Decimal

src/lazy/binary/raw/v1_1/binary_buffer.rs, src/lazy/binary/raw/v1_1/e_expression.rs, src/lazy/binary/raw/v1_1/value.rs, src/lazy/encoder/binary/v1_1/container_writers.rs, src/lazy/encoder/value_writer.rs, src/lazy/encoder/writer.rs, src/lazy/expanded/compiler.rs, src/lazy/expanded/macro_evaluator.rs, src/lazy/expanded/macro_table.rs, src/lazy/expanded/template.rs
*Issue #, if available:* #943
This PR implements the "backend" support for tagless encoding of uint8s.
By "backend" I mean that the ability to read tagless uint8s is provided, however writing them leans on a function exposed by the EExpr writer for writing `uint8`s specifically. This mirrors the support for `FlexUInt` and will require adding some functionality to existing writers to allow plumbing parameter info down so that we can verify values being written to ensure they fit the range of numeric primitives, etc., as well as handle expression groups.
```
% ./target/release/ion inspect ~/Code/sandbox/tagless_output/output.10n
┌──────────────┬──────────────┬─────────────────────────┬──────────────────────┐
│    Offset    │    Length    │       Binary Ion        │ …
```
=> Implement uint8 tagless encoding

Cargo.toml, benches/byod.rs, benches/encoding_primitives.rs, benches/write_many_structs.rs, src/lazy/encoder/writer.rs
This PR adds a 'Bring Your Own Data' benchmark that can be used to test read and write performance with any ion dataset.
---
=> Add 'bring your own data' benchmark

src/serde/de.rs
Removed variant access code in de.rs which was not letting issue #1000 and pr #999 to be resolved. 
Link to the DIFF: https://github.com/amazon-ion/ion-rust/pull/999/files#annotation_39517302043
=> Removed unused variant access code

src/lazy/encoder/binary/v1_1/value_writer.rs
#1000
Long-form timestamps were being encoded incorrectly. The encoder was encoding the timestamp as: *coefficient first, then scale*; however, it should have been *scale first, then coefficient* - as that is what the decoder is expecting. Because of the mismatch the decoder was reading the wrong bytes causing the *thousands of zeros* issue.
Example:
```
// Before fix - decoder reading wrong bytes:
Scale: 1000 (should be 9)
Coefficient: 9 (should be 1000)
Result: 0001-01-01T00:00:00.000...000009-00:00
// After fix - correct decoding:
Scale: 9
Coefficient: 1000
Result: 0001-01-01T00:00:00.000001-00:00
```
```
Original broken encoding: f8 15 01 40 04 00 fc 3f 00 a2 0f 09
^^^^^^ ^^
coefficient scale
(1000)     (9)
```
```
Fixed encoding: f8 …
```
=> Swapped to write scale then coefficient for long timestamps

src/lazy/encoder/write_as_ion.rs
#844 
Both `Element` and `&Element` implement `WriteAsIon` now
- `Element` implements it directly
- `&Element` gets it via the implementation `impl<T: WriteAsIon> WriteAsIon for &T` in `write_as_ion.rs`
This fixes the issue of `Element` not being able to implement the trait, new users can now use the API without needing to remember to add `&`.
*Example:*
```
// using this to invoke the api
// this creates an empty List using the macro and adds the annotation "valid" to the List
// then writes the annotated element to the ion stream
writer.write(ion_list![].with_annotations(["valid"]))?;
```
Before
```
// gave this error because Element did not implement WriteAsIon
error[E0277]: the trait bound `ion_rs::Element: WriteAsIon` is not …
```
=> Both `Element` and `&Element` implement `WriteAsIon` now

src/lazy/binary/raw/v1_1/value.rs, src/lazy/binary/raw/value.rs
#828 
Typed nulls in Ion 1.1 use `OpcodeType::TypedNull` encoding where the actual type information is stored in the value body. The `ion_type()` method was  only reading the header type while missing the logic to decode the actual type from the body.
Applying the typed null handling logic from `read_null()` to `ion_type()` determines if this is a typed null or regular value.
=> Move typed null handling from ion_type() to read_null() methods
