src/binary/header.rs
src/binary/int.rs
src/binary/mod.rs
src/binary/uint.rs
src/binary/var_int.rs
src/binary/var_uint.rs
src/cursor.rs
src/data_source.rs
src/lib.rs

Ran a pass of `cargo fmt` over the repository, which changed quite a bit of indenting/whitespace.
I've opened #19 to track enabling linting in the CI builds.

Cleanup w/cargo fmt

---

src/binary/cursor.rs
src/cursor.rs
src/reader.rs
tests/good.rs

* Addresses #28.
* `cargo fmt`

Changed D in `Cursor<D>` to associated type.

---

ion-c-sys/build.rs
ion-c-sys/src/lib.rs
ion-c-sys/src/reader.rs
ion-c-sys/src/result.rs
ion-c-sys/src/string.rs
ion-c-sys/src/writer.rs

Another maintenance task--add the proper copyright headers.

Adds copyright notices to ion-c-sys.

---

ion-c-sys/src/lib.rs

Small update to the writer doc test to demonstrate annotations and field name.

[ion-c-sys] Adds a richer example to the writer doc test.

---

.github/workflows/rust.yml

Refactors `rust.yml` file to use os matrix. 
A follow up PR will update the badges in the 2 README files in this repo. 

build: refactors rust.yml file

---

README.md
ion-c-sys/README.md

Updates the badges and their links in README files 
* root README
* ion-c-sys/README

Updates badges and their links in README files 

---

Cargo.toml
ion-c-sys/Cargo.toml

Specifically fills in the fields needed for publishing.

Adds Cargo.toml Metadata.

---

README.md
ion-c-sys/README.md

Adds badges for our READMEs

---

Cargo.toml
ion-c-sys/Cargo.toml

I would like to do a `cargo publish` with `BigDecimal` support.

[ion-c-sys] Bumps version to 0.3.0.

---

ion-c-sys/Cargo.toml

[ion-c-sys] Version bump for build fix.

---

.github/workflows/rust.yml
src/text/mod.rs
src/text/parsers/blob.rs
src/text/parsers/boolean.rs
src/text/parsers/decimal.rs
src/text/parsers/float.rs
src/text/parsers/integer.rs
src/text/parsers/mod.rs
src/text/parsers/null.rs
src/text/parsers/numeric_support.rs
src/text/parsers/string.rs
src/text/parsers/symbol.rs
src/text/parsers/text_support.rs
src/text/parsers/timestamp.rs
src/text/reader.rs
src/types/coefficient.rs
src/types/decimal.rs
src/types/magnitude.rs
src/types/mod.rs
src/types/timestamp.rs

Modified the CI build to run `cargo fmt --verbose -- --check` on each PR and push to make sure that the code has been formatted.
This PR contains two commits:
1. Changes to `.github/workflows/rust.yml` enabling the check
2. Another run of `rustfmt` to catch previously unformatted files caught be step \#1. 🙃 This commit touches a lot of lines but makes no logic changes.

Added rustfmt to CI tests.

---

src/text/writer.rs

*Issue #124*
This PR works on adding support for writing `clob` using text writer.
*Test:*
added test for writing `clob`.

added changes for writing clob value

---

ion-c-sys/Cargo.toml

Also bumps the patch-level version.

Updates to tip of master in ion-c.

---

ion-c-sys/Cargo.toml

Minor update to dependencies to bring them up to date.

[ion-c-sys] Updates build/dev dependencies.

---

CONTRIBUTING.md
README.md

After we rename master -> main (https://github.com/github/renaming) we
should merge this commit to fix documentation.

Prepare to rename the main branch

---

src/value/owned.rs

*Issue #153*
This PR works on creating more unit tests for `OwnedSymbolToken`.

added more unit tests for `OwnedSymbolToken`

---

src/result.rs

Adds `IonError::IonCError` to allow bridging from `ion_c_sys`.

---

ion-c-sys/Cargo.toml

[ion-c-sys] Version bump to publish binary literal fix.

---

ion-c-sys/Cargo.toml

Includes recent changes from `ion-c` (including struct seek/positioning fix). Bumps crate version accordingly.

Update ion-c to 799c4d46520659a17b3fb74cd75a52e8277e4b8f

---

ion-c-sys-macros/README.md

Adds README for `ion-c-sys` macros

---

ion-hash/src/representation.rs
src/binary/cursor.rs
src/binary/decimal.rs
src/binary/timestamp.rs
src/binary/var_int.rs
src/binary/var_uint.rs
src/binary/writer.rs

Return bytes written for timestamp/decimal encoding

---

src/binary/cursor.rs

The binary cursor's `read_datetime` method incorrectly 0-indexes
its default month and day values. If a timestamp is encountered
that only specifies a year or year+month, the default value of
zero causes the construction of a DateTime to panic.
This patch sets the default month and day values to 1.
Fixes #306.
Note that long-term, we [intend to replace `read_datetime` with a `read_timestamp` method](https://github.com/amzn/ion-rust/issues/308).

Fixes panic in read_datetime

---

src/types/timestamp.rs

*Issue #364*
This PR works on adding precision and offset methods to Timestamp type
*Test:*
Adds unit tests for precision and offset.

adds precision and offset methods to Timestamp type

---

src/value/borrowed.rs
src/value/mod.rs
src/value/owned.rs

*Issue #400*
This PR works on adding `has_annotation` method for `Element` API.
*Test:*
added doc tests for `has_annotation` in value module.

adds changes for `has_annotation` method for Element API

---

src/value/owned.rs

*Issue #, if available:* #155
*Description of changes:* I was looking at old issues here and bumped into #155- but I saw only three examples of the old `rstest`. Might as well clean them up?

Update `rstest` syntax

---

src/element/bytes.rs

None.
Implements `From` for byte literals.

Adds conversion from byte literals to Bytes

---

src/types/timestamp.rs

This PR updates the `Ord` implementation of `Timestamp` to consider value of the timestamp rather then precision when a timestamp with fractional second is compared to a timestamp without fractional seconds (i.e. `fractional_seconds` as `None`).
*Sample timestamps for the issue:*
```
// both the timestamps below should be equal
2020-01-01T00:00:00Z
2020-01-01T00:00:00.000000000Z
```
*Issue:*
Timestamp `Ord` implementation didn't consider the value of the timestamp when a timestamp with fractional seconds was compared to a timestamp without fractional seconds. 

updates `Ord` implementation of `Timestamp`

---

Cargo.toml
src/ion_hash/type_qualifier.rs

Version bump to v0.18.0

---

src/lazy/encoder/binary/v1_0/value_writer.rs
src/lazy/encoder/binary/v1_1/value_writer.rs
src/lazy/encoder/text/value_writer.rs
src/lazy/encoder/write_as_ion.rs

Incorporates feedback from PR #686

---

src/lazy/encoder/binary/v1_1/value_writer.rs

Implements writing v1.1 decimals

---

src/reader.rs

This PR adds implementation of reader builder which allows adding catalog information to the reader. 
- Changes `ReaderBuilder` to store catalog information
- adds `with_catalog()` to add catalog information to builder

Adds implementation for reader builder with catalog

---

Cargo.toml

Version bump in preparation for a new release.

Version bump to v1.0.0-rc.2

---

Cargo.toml

Version bump in preparation for `v1.0.0-rc.3` release.

Verion bump to 1.0.0-rc.3

---

src/lazy/binary/raw/v1_1/immutable_buffer.rs
src/lazy/binary/raw/v1_1/reader.rs
src/lazy/binary/raw/v1_1/type_code.rs
src/lazy/binary/raw/v1_1/type_descriptor.rs
src/lazy/binary/raw/v1_1/value.rs
src/lazy/encoder/binary/v1_1/fixed_int.rs

*Issue #, if available:* #662
This PR continues the 1.1 binary reader value PR chain with strings and integers.
---

Add 1.1 binary reader support for strings and integers.

---

src/lazy/binary/raw/v1_1/immutable_buffer.rs
src/lazy/binary/raw/v1_1/reader.rs
src/lazy/binary/raw/v1_1/type_descriptor.rs
src/lazy/binary/raw/v1_1/value.rs

Add support for Symbols to the 1.1 binary raw reader.
---

Add 1.1 binary reader support for symbols

---

src/lazy/system_reader.rs

Incorporates feedback from PR #777 that arrived post-merge.

incorporates minor feedback from PR #777

---

Cargo.toml

Version bump in anticipation of cutting a new release candidate.

Version bump to 1.0.0-rc.4

---

Cargo.toml

Version bump to rc5

---

Cargo.toml

Version bump to v1.0.0-rc.7

---

src/element/sequence.rs
src/lazy/any_encoding.rs
src/lazy/binary/raw/v1_1/e_expression.rs
src/lazy/expanded/compiler.rs
src/lazy/expanded/e_expression.rs
src/lazy/expanded/macro_evaluator.rs
src/lazy/expanded/macro_table.rs
src/lazy/expanded/mod.rs
src/lazy/expanded/sequence.rs
src/lazy/expanded/struct.rs
src/lazy/expanded/template.rs
src/lazy/never.rs
src/lazy/system_reader.rs
src/lazy/text/raw/v1_1/arg_group.rs
src/lazy/value.rs

Adds TDL expr groups, `append_macros` system macro

---

Cargo.toml

None
Sets version to 1.0.0-rc.8

Version bump to v1.0.0-rc.8

---

Cargo.toml

Version bump to v1.0.0-rc.9

---

Cargo.toml

Version bump to v1.0.0-rc.11

---

src/ion_data/mod.rs
src/ion_hash/type_qualifier.rs

None
Implements `WriteAsIon` for `IonData`

Implement WriteAsIon for IonData

---

src/element/mod.rs
src/lazy/value.rs

This PR adds location metadata support for `Element` API.

Adds location metadata support for `Element` API

---

src/element/mod.rs
src/lazy/expanded/mod.rs
src/lazy/value.rs
src/lib.rs
src/location.rs

*Issue #948*
This PR works on adding a `SourceLocation` wrapper for location metadata.

Adds implementation of SourceLocation

---

src/lazy/encoder/writer.rs

Fixes #939.
Prior to this change, `Writer::flush` would `flush()` its inner directive raw writer and its inner data raw writer, but didn't flush the output sink. This went undetected because:
1. Writing to a `Vec<u8>` doesn't require a `flush()` operation.
2. Writing to a `File` does require a `flush()` operation, but `flush()` is called automatically when the `File` is dropped.
In both cases, correctness was not affected. In case 2, the entire output stream would end up being buffered before finally being written out.

`Writer::flush` now also flushes underlying sink

---

src/lazy/decoder.rs
src/lazy/value.rs

Fixes clippy warnings

---

src/lazy/any_encoding.rs
src/lazy/binary/binary_buffer.rs
src/lazy/binary/raw/v1_1/binary_buffer.rs
src/lazy/binary/raw/v1_1/e_expression.rs
src/lazy/encoder/binary/v1_1/fixed_int.rs
src/lazy/encoder/binary/v1_1/flex_uint.rs
src/lazy/expanded/e_expression.rs
src/lazy/expanded/macro_evaluator.rs
src/lazy/expanded/mod.rs
src/lazy/expanded/struct.rs
src/lazy/expanded/template.rs
src/lazy/never.rs
src/lazy/text/raw/v1_1/arg_group.rs
src/lazy/text/raw/v1_1/reader.rs

Binary 1.1 optimizations including Improved inlining, type layout shrinking

---

src/lazy/expanded/template.rs
src/types/integer.rs

Also `cargo fmt` fixed `src/lazy/expanded/template.rs`.

Implement Sub for Int

---

tests/conformance_tests.rs

This PR removes entries from the skip-list that were recently deleted in `ion-tests`.
It also adds a small unit test that is ignored by default, but can be used to check that the skip-list entries exist.
---

chore: skiplist maintenance
